-- ALTER A NUESTRAS TABLAS PARA AGREGAR LOS ATRIBUTOS DE LA AUDITORIA POR TUPLAS
ALTER TABLE FIDE_ALIMENTACION_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_ANIMAL_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/


ALTER TABLE FIDE_CANTON_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_CATEGORIA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DETALLE_ENTREGA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DETALLE_FACTURA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DIRECCION_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_DISTRITO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_EMPRESA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_ENTREGA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_ESTADOS_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_FACTURA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_GENERO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_HABITAT_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_HORARIO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_INVENTARIO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_MARCA_ALIMENTO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/


ALTER TABLE FIDE_METODO_PAGO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PAIS_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PRODUCTO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_PROVINCIA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_ROL_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_RUTINA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_TIPO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_UNIDAD_MEDIDA_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

ALTER TABLE FIDE_USUARIO_TB
ADD (
FECHA_CREACION TIMESTAMP,
FECHA_MODIFICACION TIMESTAMP,
CREADO_POR VARCHAR2(100),
MODIFICADO_POR VARCHAR2(100),
ACCION VARCHAR2(100)
);
/

--SECUENCIAS PARA AUTOMATIZAR ID'S
CREATE SEQUENCE ID_ANIMAL_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_CANTON_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_CATEGORIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_DIRECCION_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_DISTRITO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_EMPRESA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_ENTREGA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_ESTADOS_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_FACTURA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_GENERO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_HABITAT_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_HORARIO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_MARCA_ALIMENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_METODO_PAGO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_PAIS_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_PRODUCTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_PROVINCIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_ROL_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_RUTINA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_TIPO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_UNIDAD_MEDIDA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ID_USUARIO_SEQ
START WITH 1
INCREMENT BY 1;
/

-- FUNCION PARA GENERAR EL ID ESPECIAL EN NUESTRAS FACTURAS
CREATE OR REPLACE FUNCTION GENERAR_SECUENCIA_FACTURA_FN
RETURN NUMBER AS
V_FECHA VARCHAR2(8);
V_VALOR NUMBER;
BEGIN
V_FECHA:= TO_CHAR(SYSDATE, 'YYYYMMDD');
V_VALOR:= TO_NUMBER(V_FECHA || LPAD (ID_FACTURA_SEQ.NEXTVAL, 4, '0'));
RETURN V_VALOR;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ALIMENTACION_INSERT_TRG
BEFORE INSERT ON FIDE_ALIMENTACION_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ALIMENTACION_UPDATE_TRG
BEFORE UPDATE ON FIDE_ALIMENTACION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ANIMAL_INSERT_TRG
BEFORE INSERT ON FIDE_ANIMAL_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
  :NEW.ID_ANIMAL := ID_ANIMAL_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ANIMAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_ANIMAL_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_INSERT_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
  :NEW.ID_CANTON := ID_CANTON_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_CATEGORIA := ID_CATEGORIA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_ENTREGA_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_ENTREGA_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_ENTREGA_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_ENTREGA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_DIRECCION := ID_DIRECCION_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_DISTRITO := ID_DISTRITO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPRESA_INSERT_TRG
BEFORE INSERT ON FIDE_EMPRESA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_EMPRESA := ID_EMPRESA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPRESA_UPDATE_TRG
BEFORE UPDATE ON FIDE_EMPRESA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ENTREGA_INSERT_TRG
BEFORE INSERT ON FIDE_ENTREGA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_ENTREGA := ID_ENTREGA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ENTREGA_UPDATE_TRG
BEFORE UPDATE ON FIDE_ENTREGA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_ESTADO := ID_ESTADOS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_FACTURA := GENERAR_SECUENCIA_FACTURA_FN;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_GENERO_INSERT_TRG
BEFORE INSERT ON FIDE_GENERO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_GENERO := ID_GENERO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_GENERO_UPDATE_TRG
BEFORE UPDATE ON FIDE_GENERO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_HABITAT_INSERT_TRG
BEFORE INSERT ON FIDE_HABITAT_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_HABITAT := ID_HABITAT_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_HABITAT_UPDATE_TRG
BEFORE UPDATE ON FIDE_HABITAT_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_HORARIO_INSERT_TRG
BEFORE INSERT ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_HORARIO := ID_HORARIO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_HORARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_HORARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_INSERT_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_ALIMENTO_INSERT_TRG
BEFORE INSERT ON FIDE_MARCA_ALIMENTO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
  :NEW.ID_MARCA_ALIMENTO := ID_MARCA_ALIMENTO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_ALIMENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MARCA_ALIMENTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_INSERT_TRG
BEFORE INSERT ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_METODO_PAGO := ID_METODO_PAGO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_UPDATE_TRG
BEFORE UPDATE ON FIDE_METODO_PAGO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_INSERT_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_PAIS := ID_PAIS_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_INSERT_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_PRODUCTO := ID_PRODUCTO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_PROVINCIA := ID_PROVINCIA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROL_INSERT_TRG
BEFORE INSERT ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_ROL := ID_ROL_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROL_UPDATE_TRG
BEFORE UPDATE ON FIDE_ROL_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_RUTINA_INSERT_TRG
BEFORE INSERT ON FIDE_RUTINA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_RUTINA := ID_RUTINA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_RUTINA_UPDATE_TRG
BEFORE UPDATE ON FIDE_RUTINA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_TIPO := ID_TIPO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_UNIDAD_MEDIDA_INSERT_TRG
BEFORE INSERT ON FIDE_UNIDAD_MEDIDA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_CREACION:= SYSTIMESTAMP;
:NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'INSERT';
:NEW.ID_UNIDAD_MEDIDA := ID_UNIDAD_MEDIDA_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_UNIDAD_MEDIDA_UPDATE_TRG
BEFORE UPDATE ON FIDE_UNIDAD_MEDIDA_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
  :NEW.ACCION := 'INSERT';
  :NEW.ID_USUARIO := ID_USUARIO_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
:NEW.FECHA_MODIFICACION:= SYSTIMESTAMP;
:NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
:NEW.ACCION := 'UPDATE';
END;
/