
CREATE TABLE FIDE_PAIS_TB (
    ID_PAIS     NUMBER,
    NOMBRE_PAIS VARCHAR2(50),
    ID_ESTADO   NUMBER,
    CONSTRAINT FIDE_PAIS_PK PRIMARY KEY (ID_PAIS),
    CONSTRAINT FIDE_PAIS_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);


CREATE TABLE FIDE_PROVINCIA_TB (
    ID_PROVINCIA     NUMBER,
    NOMBRE_PROVINCIA VARCHAR2(50),
    ID_ESTADO        NUMBER,
    CONSTRAINT FIDE_PROVINCIA_PK PRIMARY KEY (ID_PROVINCIA),
    CONSTRAINT FIDE_PROVINCIA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);


CREATE TABLE FIDE_CANTON_TB (
    ID_CANTON     NUMBER,
    NOMBRE_CANTON VARCHAR2(50),
    ID_ESTADO     NUMBER,
    CONSTRAINT FIDE_CANTON_PK PRIMARY KEY (ID_CANTON),
    CONSTRAINT FIDE_CANTON_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_DISTRITO_TB (
    ID_DISTRITO     NUMBER,
    NOMBRE_DISTRITO VARCHAR2(50),
    ID_ESTADO       NUMBER,
    CONSTRAINT FIDE_DISTRITO_PK PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT FIDE_DISTRITO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);


CREATE TABLE FIDE_DIRECCION_TB (
    ID_DIRECCION        NUMBER,
    DETALLE_DIRECCION   VARCHAR2(100),
    ID_DISTRITO         NUMBER,
    ID_CANTON           NUMBER,
    ID_PROVINCIA        NUMBER,
    ID_PAIS             NUMBER,
    ID_USUARIO          NUMBER,
    ID_ESTADO           NUMBER,
    CONSTRAINT FIDE_DIRECCION_PK PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FIDE_DIRECCION_DISTRITO_FK FOREIGN KEY (ID_DISTRITO)
        REFERENCES FIDE_DISTRITO_TB(ID_DISTRITO),
    CONSTRAINT FIDE_DIRECCION_CANTON_FK FOREIGN KEY (ID_CANTON)
        REFERENCES FIDE_CANTON_TB(ID_CANTON),
    CONSTRAINT FIDE_DIRECCION_PROVINCIA_FK FOREIGN KEY (ID_PROVINCIA)
        REFERENCES FIDE_PROVINCIA_TB(ID_PROVINCIA),
    CONSTRAINT FIDE_DIRECCION_PAIS_FK FOREIGN KEY (ID_PAIS)
        REFERENCES FIDE_PAIS_TB(ID_PAIS),
    CONSTRAINT FIDE_DIRECCION_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)

);

CREATE TABLE FIDE_EMPRESA_TB (
    ID_EMPRESA       NUMBER,
    NOMBRE_EMPRESA   VARCHAR2(100),
    TELEFONO         VARCHAR2(20),
    CORREO           VARCHAR2(100),
    ID_DIRECCION     NUMBER,
    ID_ESTADO        NUMBER,
    CONSTRAINT FIDE_EMPRESA_PK PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT FIDE_EMPRESA_DIRECCION_FK FOREIGN KEY (ID_DIRECCION)
        REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
    CONSTRAINT FIDE_EMPRESA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);


