CREATE TABLE FIDE_ROL_TB (
    ID_ROL                NUMBER,
    NOMBRE_ROL    VARCHAR2(100),
    DESCRIPCION     VARCHAR2(100),
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_ROL_PK PRIMARY KEY (ID_ROL),
 
    -- Claves foráneas
    CONSTRAINT FIDE_ROL_ESTADO_FK FOREIGN KEY (ID_ESTADO)
     REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_USUARIO_TB (
    ID_USUARIO                NUMBER,
    NOMBRE                      VARCHAR2(100),
    FECHA_REGISTRO       DATE,
    TELEFONO                    VARCHAR2(20),
    CORREO                       VARCHAR2(100),
    ID_ESTADO                   NUMBER,
    ID_ROL                          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_USUARIO_PK PRIMARY KEY (ID_USUARIO),
 
    -- Claves foráneas
    CONSTRAINT FIDE_USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    
    CONSTRAINT FIDE_USUARIO_ROL_FK FOREIGN KEY (ID_ROL)
    REFERENCES FIDE_ROL_TB(ID_ROL)    
);
/

CREATE TABLE FIDE_HORARIO_TB (
    ID_HORARIO     NUMBER,
    DIA                     VARCHAR2(10),
    HORA_INICIO    DATE,
    HORA_FINAL     DATE,
    ID_USUARIO       NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_HORARIO_PK PRIMARY KEY (ID_HORARIO),
 
    -- Claves foráneas
     CONSTRAINT FIDE_HORARIO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
     REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
     
    CONSTRAINT FIDE_HORARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
     REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_ENTREGA_TB (
    ID_ENTREGA       NUMBER,
    FECHA                  DATE,
    ID_DIRECCION    NUMBER,
    ID_USUARIO        NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_ENTREGA_PK PRIMARY KEY (ID_ENTREGA),
 
    -- Claves foráneas
    CONSTRAINT FIDE_ENTREGA_DIRECCION_FK FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
        
    CONSTRAINT FIDE_ENTREGA_USUARIO_FK FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
        
    CONSTRAINT FIDE_ENTREGA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DETALLE_ENTREGA_TB (
    ID_DETALLE         NUMBER, 
    DESCRIPCION     VARCHAR2(100),
    CANTIDAD           NUMBER,
    ID_ENTREGA        NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_DETALLE_ENTREGA_PK PRIMARY KEY (ID_DETALLE),
 
    -- Claves foráneas
    CONSTRAINT FIDE_DETALLE_ENTREGA_FK FOREIGN KEY (ID_ENTREGA)
    REFERENCES FIDE_ENTREGA_TB(ID_ENTREGA),
    
    CONSTRAINT FIDE_DETALLE_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
