CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_PCK AS
--TABLA DE ESTADOS
PROCEDURE FIDE_INSERTAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
);

--TABLA DE GENERO
--INSERTAR
PROCEDURE FIDE_INSERTAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE
);

--TABLA DE TIPO
--INSERTAR
PROCEDURE FIDE_INSERTAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE
);

--TABLA DE HABITAT
--INSERTAR
PROCEDURE FIDE_INSERTAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE
);

--TABLA DE RUTINA
--INSERTAR
PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
);

--TABLA DE MARCA_ALIMENTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE
);

--TABLA DE ALIMENTACION
--INSERTAR
PROCEDURE FIDE_INSERTAR_ALIMENTACION_SP(
P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
    P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
    P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
    P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
    P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
    P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
    P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE
);

--TABLA DE ANIMAL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ANIMAL_SP(
P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
    P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
    P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
    P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
    P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
    P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
    P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
    P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
    P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
    P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
    P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE
);

--TABLA DE ROL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE
);

--TABLA DE USUARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_USUARIO_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
    P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
    P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
    P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
    P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE
);

--TABLA DE HORARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_HORARIO_SP(
P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
    P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
    P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
    P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
    P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE
);

--TABLA DE PAIS
--INSERTAR
PROCEDURE FIDE_INSERTAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
);

--TABLA DE PROVINCIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
);

--TABLA DE CANTON
--INSERTAR
PROCEDURE FIDE_INSERTAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
);

--TABLA DE DISTRITO
--INSERTAR
PROCEDURE FIDE_INSERTAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
);

--TABLA DIRECCION
--INSERTAR
PROCEDURE FIDE_INSERTAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_USUARIO IN FIDE_DIRECCION_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_USUARIO IN FIDE_DIRECCION_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DIRECCION_SP(
    P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
);

--TABLA DE EMPRESA
--INSERTAR
PROCEDURE FIDE_INSERTAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE
);

--TABLA DE ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_ENTREGA_SP(
P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ENTREGA_SP(
   P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
    P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
    P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ENTREGA_SP(
    P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE
);

--TABLA DE DETALLE_ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_ENTREGA_SP(
P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE,
P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_ENTREGA_SP(
   P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE,
    P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
    P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
    P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_ENTREGA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE
);

--TABLA DE CATEGORIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
);

--TABLA DE UNIDAD_MEDIDA
--INSERTAR
PROCEDURE FIDE_INSERTAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE
);

--TABLA DE PRODUCTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_PRODUCTO_SP(
P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PRODUCTO_SP(
   P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
    P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
    P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PRODUCTO_SP(
    P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
);

--TABLA DE INVENTARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_INVENTARIO_SP(
P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_INVENTARIO_SP(
   P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_INVENTARIO_SP(
    P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE
);

--TABLA DE METODO_PAGO
--INSERTAR
PROCEDURE FIDE_INSERTAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
);

--TABLA DE FACTURA
--INSERTAR 
PROCEDURE FIDE_INSERTAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_FACTURA_SP(
    P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
);

--TABLA DETALLE_FACTURA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_FACTURA_SP(
P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE,
P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_FACTURA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE,
    P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_FACTURA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE
);

END FIDE_PROYECTO_FINAL_PCK;
/

CREATE OR REPLACE PACKAGE BODY FIDE_PROYECTO_FINAL_PCK AS

---PROCEDIMIENTOS ALMACENADOS (CRUD DE TODAS LAS TABLAS)
--TABLA DE ESTADOS
--INSERTAR
PROCEDURE FIDE_INSERTAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION_ESTADO)
   VALUES(P_ID_ESTADO, P_NOMBRE_ESTADO, P_DESCRIPCION_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ESTADO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO,
            DESCRIPCION_ESTADO = P_DESCRIPCION_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ESTADO_SP;


--TABLA DE GENERO
--INSERTAR
PROCEDURE FIDE_INSERTAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_GENERO_TB (ID_GENERO, GENERO, ID_ESTADO)
   VALUES(P_ID_GENERO, P_GENERO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_GENERO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET GENERO = P_GENERO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_GENERO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET ID_ESTADO = 2
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_GENERO_SP;


--TABLA DE TIPO
--INSERTAR
PROCEDURE FIDE_INSERTAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_TIPO_TB (ID_TIPO, NOMBRE_TIPO, DESCRIPCION_TIPO, ID_ESTADO)
   VALUES(P_ID_TIPO, P_NOMBRE_TIPO, P_DESCRIPCION_TIPO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_TIPO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET NOMBRE_TIPO = P_NOMBRE_TIPO,
            DESCRIPCION_TIPO = P_DESCRIPCION_TIPO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_TIPO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_TIPO_SP;


--TABLA DE HABITAT
--INSERTAR
PROCEDURE FIDE_INSERTAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_HABITAT_TB (ID_HABITAT, NOMBRE_HABITAT, DESCRIPCION_HABITAT, ID_ESTADO)
   VALUES(P_ID_HABITAT, P_NOMBRE_HABITAT, P_DESCRIPCION_HABITAT, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_HABITAT_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET NOMBRE_HABITAT = P_NOMBRE_HABITAT,
            DESCRIPCION_HABITAT = P_DESCRIPCION_HABITAT,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_HABITAT_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET ID_ESTADO = 2
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_HABITAT_SP;


--TABLA DE RUTINA
--INSERTAR
PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_RUTINA_TB (ID_RUTINA, NOMBRE_RUTINA, ID_ESTADO)
   VALUES(P_ID_RUTINA, P_NOMBRE_RUTINA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_RUTINA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET NOMBRE_RUTINA = P_NOMBRE_RUTINA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_RUTINA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET ID_ESTADO = 2
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_RUTINA_SP;


--TABLA DE MARCA_ALIMENTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_MARCA_ALIMENTO_TB (ID_MARCA_ALIMENTO, NOMBRE, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_MARCA_ALIMENTO, P_NOMBRE, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_MARCA_ALIMENTO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET NOMBRE = P_NOMBRE,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_MARCA_ALIMENTO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET ID_ESTADO = 2
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_MARCA_ALIMENTO_SP;


--TABLA DE ALIMENTACION
--INSERTAR
PROCEDURE FIDE_INSERTAR_ALIMENTACION_SP(
P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ALIMENTACION_TB (ID_ALIMENTACION, CANTIDAD, HORARIO, FRECUENCIA, ID_MARCA_ALIMENTO, ID_ESTADO, ID_RUTINA) 
   VALUES(P_ID_ALIMENTACION, P_CANTIDAD, P_HORARIO, P_FRECUENCIA, P_ID_MARCA_ALIMENTO, P_ID_ESTADO, P_ID_RUTINA);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ALIMENTACION_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
    P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
    P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
    P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
    P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
    P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
    P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
    UPDATE FIDE_ALIMENTACION_TB
    SET CANTIDAD = P_CANTIDAD,
            HORARIO = P_HORARIO,
            FRECUENCIA = P_FRECUENCIA,
            ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO,
            ID_ESTADO = P_ID_ESTADO,
            ID_RUTINA = P_ID_RUTINA
    WHERE ID_ALIMENTACION = P_ID_ALIMENTACION; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ALIMENTACION_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE
)IS
BEGIN
    UPDATE FIDE_ALIMENTACION_TB
    SET ID_ESTADO = 2
    WHERE ID_ALIMENTACION = P_ID_ALIMENTACION;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ALIMENTACION_SP;


--TABLA DE ANIMAL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ANIMAL_SP(
P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ANIMAL_TB (ID_ANIMAL, NOMBRE_ANIMAL, FECHA_INGRESO, EDAD, PESO, OBSERVACION, ID_GENERO, ID_TIPO, ID_HABITAT, ID_ESTADO, ID_ALIMENTACION) 
   VALUES(P_ID_ANIMAL, P_NOMBRE_ANIMAL, P_FECHA_INGRESO, P_EDAD, P_PESO, P_OBSERVACION, P_ID_GENERO, P_ID_TIPO, P_ID_HABITAT, P_ID_ESTADO, P_ID_ALIMENTACION);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ANIMAL_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
    P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
    P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
    P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
    P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
    P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
    P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
    P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
    P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
    P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
    P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
) IS
BEGIN
    UPDATE FIDE_ANIMAL_TB
    SET NOMBRE_ANIMAL = P_NOMBRE_ANIMAL,
            FECHA_INGRESO = P_FECHA_INGRESO,
            EDAD = P_EDAD,
            PESO = P_PESO,
            OBSERVACION = P_OBSERVACION,
            ID_GENERO = P_ID_GENERO,
            ID_TIPO = P_ID_TIPO,
            ID_HABITAT = P_ID_HABITAT,
            ID_ESTADO = P_ID_ESTADO,
            ID_ALIMENTACION = P_ID_ALIMENTACION
    WHERE ID_ANIMAL = P_ID_ANIMAL; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ANIMAL_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE
)IS
BEGIN
    UPDATE FIDE_ANIMAL_TB
    SET ID_ESTADO = 2
    WHERE ID_ANIMAL = P_ID_ANIMAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ANIMAL_SP;


--TABLA DE ROL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_ROL, P_NOMBRE_ROL, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ROL_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET NOMBRE_ROL = P_NOMBRE_ROL,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ROL_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET ID_ESTADO = 2
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ROL_SP;


--TABLA DE USUARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_USUARIO_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
   INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE, FECHA_REGISTRO, TELEFONO, CORREO, ID_ESTADO, ID_ROL) 
   VALUES(P_ID_USUARIO, P_NOMBRE, P_FECHA_REGISTRO, P_TELEFONO, P_CORREO, P_ID_ESTADO, P_ID_ROL);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_USUARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
    P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
    P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
    P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
    P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET NOMBRE = P_NOMBRE,
            FECHA_REGISTRO = P_FECHA_REGISTRO,
            TELEFONO = P_TELEFONO,
            CORREO = P_CORREO,
            ID_ESTADO = P_ID_ESTADO,
            ID_ROL = P_ID_ROL
    WHERE ID_USUARIO = P_ID_USUARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_USUARIO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_USUARIO = P_ID_USUARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_USUARIO_SP;


--TABLA DE HORARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_HORARIO_SP(
P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_HORARIO_TB (ID_HORARIO, DIA, HORA_INICIO, HORA_FINAL, ID_USUARIO, ID_ESTADO) 
   VALUES(P_ID_HORARIO, P_DIA, P_HORA_INICIO, P_HORA_FINAL, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_HORARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
    P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
    P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
    P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
    P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_HORARIO_TB
    SET DIA = P_DIA,
            HORA_INICIO = P_HORA_INICIO,
            HORA_FINAL = P_HORA_FINAL,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_HORARIO = P_ID_HORARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_HORARIO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_HORARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_HORARIO = P_ID_HORARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_HORARIO_SP;


--TABLA DE PAIS
--INSERTAR
PROCEDURE FIDE_INSERTAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PAIS_TB (ID_PAIS, NOMBRE_PAIS, ID_ESTADO)
   VALUES(P_ID_PAIS, P_NOMBRE_PAIS, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PAIS_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET NOMBRE_PAIS = P_NOMBRE_PAIS,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PAIS_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET ID_ESTADO = 2
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PAIS_SP;


--TABLA DE PROVINCIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA, ID_ESTADO)
   VALUES(P_ID_PROVINCIA, P_NOMBRE_PROVINCIA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PROVINCIA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET NOMBRE_PROVINCIA = P_NOMBRE_PROVINCIA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PROVINCIA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET ID_ESTADO = 2
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PROVINCIA_SP;


--TABLA DE CANTON
--INSERTAR
PROCEDURE FIDE_INSERTAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_ESTADO)
   VALUES(P_ID_CANTON, P_NOMBRE_CANTON, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_CANTON_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET NOMBRE_CANTON = P_NOMBRE_CANTON,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_CANTON_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET ID_ESTADO = 2
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_CANTON_SP;


--TABLA DE DISTRITO
--INSERTAR
PROCEDURE FIDE_INSERTAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_ESTADO)
   VALUES(P_ID_DISTRITO, P_NOMBRE_DISTRITO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DISTRITO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET NOMBRE_DISTRITO = P_NOMBRE_DISTRITO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DISTRITO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET ID_ESTADO = 2
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DISTRITO_SP;


--TABLA DIRECCION
--TABLA DIRECCION
--INSERTAR
PROCEDURE FIDE_INSERTAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_USUARIO IN FIDE_DIRECCION_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DIRECCION_TB(id_DIRECCION, DETALLE_DIRECCION, ID_DISTRITO, ID_CANTON, ID_PROVINCIA, ID_PAIS, ID_USUARIO, ID_ESTADO) 
   VALUES(P_ID_DIRECCION, P_DETALLE_DIRECCION, P_ID_DISTRITO, P_ID_CANTON, P_ID_PROVINCIA, P_ID_PAIS, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DIRECCION_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_USUARIO IN FIDE_DIRECCION_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DIRECCION_TB
    SET DETALLE_DIRECCION = P_DETALLE_DIRECCION,
            ID_DISTRITO = P_ID_DISTRITO,
            ID_CANTON = P_ID_CANTON,
            ID_PROVINCIA = P_ID_PROVINCIA,
            ID_PAIS = P_ID_PAIS,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DIRECCION = P_ID_DIRECCION; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DIRECCION_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DIRECCION_SP(
    P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
)IS
BEGIN
    UPDATE FIDE_DIRECCION_TB
    SET ID_ESTADO = 2
    WHERE ID_DIRECCION = P_ID_DIRECCION;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DIRECCION_SP;


--TABLA DE EMPRESA
--INSERTAR
PROCEDURE FIDE_INSERTAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_EMPRESA_TB(ID_EMPRESA, NOMBRE_EMPRESA, TELEFONO, CORREO, ID_DIRECCION, ID_ESTADO) 
   VALUES(P_ID_EMPRESA, P_NOMBRE_EMPRESA, P_TELEFONO, P_CORREO, P_ID_DIRECCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_EMPRESA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_EMPRESA_TB
    SET NOMBRE_EMPRESA = P_NOMBRE_EMPRESA,
            TELEFONO = P_TELEFONO,
            CORREO = P_CORREO,
            ID_DIRECCION = P_ID_DIRECCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_EMPRESA = P_ID_EMPRESA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_EMPRESA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE
)IS
BEGIN
    UPDATE FIDE_EMPRESA_TB
    SET ID_ESTADO = 2
    WHERE ID_EMPRESA = P_ID_EMPRESA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_EMPRESA_SP;


--TABLA DE ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_ENTREGA_SP(
P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ENTREGA_TB(ID_ENTREGA, FECHA, ID_DIRECCION, ID_USUARIO,ID_ESTADO) 
   VALUES(P_ID_ENTREGA, P_FECHA, P_ID_DIRECCION, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ENTREGA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ENTREGA_SP(
   P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
    P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
    P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ENTREGA_TB
    SET FECHA = P_FECHA,
            ID_DIRECCION = P_ID_DIRECCION,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_ENTREGA = P_ID_ENTREGA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ENTREGA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ENTREGA_SP(
    P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE
)IS
BEGIN
    UPDATE FIDE_ENTREGA_TB
    SET ID_ESTADO = 2
    WHERE ID_ENTREGA = P_ID_ENTREGA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ENTREGA_SP;


--TABLA DE DETALLE_ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_ENTREGA_SP(
P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE,
P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DETALLE_ENTREGA_TB(ID_DETALLE, DESCRIPCION, CANTIDAD, ID_ENTREGA,ID_ESTADO) 
   VALUES(P_ID_DETALLE, P_DESCRIPCION, P_CANTIDAD, P_ID_ENTREGA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DETALLE_ENTREGA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_ENTREGA_SP(
   P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE,
    P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
    P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
    P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DETALLE_ENTREGA_TB
    SET DESCRIPCION = P_DESCRIPCION,
            CANTIDAD = P_CANTIDAD,
            ID_ENTREGA = P_ID_ENTREGA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DETALLE = P_ID_DETALLE; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DETALLE_ENTREGA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_ENTREGA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_ENTREGA_TB.ID_DETALLE%TYPE
)IS
BEGIN
    UPDATE FIDE_DETALLE_ENTREGA_TB
    SET ID_ESTADO = 2
    WHERE ID_DETALLE = P_ID_DETALLE;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DETALLE_ENTREGA_SP;


--TABLA DE CATEGORIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_CATEGORIA_TB (ID_CATEGORIA, NOMBRE_CATEGORIA, ID_ESTADO)
   VALUES(P_ID_CATEGORIA, P_NOMBRE_CATEGORIA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_CATEGORIA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET NOMBRE_CATEGORIA = P_NOMBRE_CATEGORIA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_CATEGORIA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
)IS
    BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET ID_ESTADO = 2
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_CATEGORIA_SP;


--TABLA DE UNIDAD_MEDIDA
--INSERTAR
PROCEDURE FIDE_INSERTAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_UNIDAD_MEDIDA_TB (ID_UNIDAD_MEDIDA, NOMBRE_UNIDAD_MEDIDA, ID_ESTADO)
   VALUES(P_ID_UNIDAD_MEDIDA, P_NOMBRE_UNIDAD_MEDIDA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_UNIDAD_MEDIDA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_UNIDAD_MEDIDA_TB
    SET NOMBRE_UNIDAD_MEDIDA = P_NOMBRE_UNIDAD_MEDIDA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_UNIDAD_MEDIDA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE
)IS
    BEGIN
    UPDATE FIDE_UNIDAD_MEDIDA_TB
    SET ID_ESTADO = 2
    WHERE ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_UNIDAD_MEDIDA_SP;


--TABLA DE PRODUCTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_PRODUCTO_SP(
P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PRODUCTO_TB(ID_PRODUCTO, NOMBRE, ID_CATEGORIA, ID_UNIDAD_MEDIDA,ID_ESTADO) 
   VALUES(P_ID_PRODUCTO, P_NOMBRE, P_ID_CATEGORIA, P_ID_UNIDAD_MEDIDA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PRODUCTO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PRODUCTO_SP(
   P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
    P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
    P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_PRODUCTO_TB
    SET NOMBRE = P_NOMBRE,
            ID_CATEGORIA = P_ID_CATEGORIA,
            ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PRODUCTO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PRODUCTO_SP(
    P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
)IS
BEGIN
    UPDATE FIDE_PRODUCTO_TB
    SET ID_ESTADO = 2
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PRODUCTO_SP;


--TABLA DE INVENTARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_INVENTARIO_SP(
P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_INVENTARIO_TB(ID_INVENTARIO, CANTIDAD, FECHA_INGRESO, ID_PRODUCTO,ID_ESTADO) 
   VALUES(P_ID_INVENTARIO, P_CANTIDAD, P_FECHA_INGRESO, P_ID_PRODUCTO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_INVENTARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_INVENTARIO_SP(
   P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB
    SET CANTIDAD = P_CANTIDAD,
            FECHA_INGRESO = P_FECHA_INGRESO,
            ID_PRODUCTO = P_ID_PRODUCTO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_INVENTARIO = P_ID_INVENTARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_INVENTARIO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_INVENTARIO_SP(
    P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_INVENTARIO = P_ID_INVENTARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_INVENTARIO_SP;


--TABLA DE METODO_PAGO
--INSERTAR
PROCEDURE FIDE_INSERTAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_METODO_PAGO_TB (ID_METODO_PAGO, NOMBRE_METODO_PAGO, ID_ESTADO)
   VALUES(P_ID_METODO_PAGO, P_NOMBRE_METODO_PAGO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_METODO_PAGO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_METODO_PAGO_TB
    SET NOMBRE_METODO_PAGO = P_NOMBRE_METODO_PAGO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_METODO_PAGO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
)IS
    BEGIN
    UPDATE FIDE_METODO_PAGO_TB
    SET ID_ESTADO = 2
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_METODO_PAGO_SP;


--TABLA DE FACTURA
--INSERTAR 
PROCEDURE FIDE_INSERTAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_FACTURA_TB(ID_FACTURA, FECHA_REGISTRO, MONTO_TOTAL, SUBTOTAL, IVA, DESCUENTO, ID_USUARIO, ID_METODO_PAGO, ID_ESTADO) 
   VALUES(P_ID_FACTURA, P_FECHA_REGISTRO, P_MONTO_TOTAL, P_SUBTOTAL, P_IVA, P_DESCUENTO,  P_ID_USUARIO, P_ID_METODO_PAGO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_FACTURA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET FECHA_REGISTRO = P_FECHA_REGISTRO,
            MONTO_TOTAL = P_MONTO_TOTAL,
            SUBTOTAL = P_SUBTOTAL,
            IVA = P_IVA,
            DESCUENTO = P_DESCUENTO,
            ID_USUARIO = P_ID_USUARIO,
            ID_METODO_PAGO = P_ID_METODO_PAGO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_FACTURA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_FACTURA_SP(
    P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
)IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET ID_ESTADO = 2
    WHERE ID_FACTURA = P_ID_FACTURA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_FACTURA_SP;


--TABLA DETALLE_FACTURA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_FACTURA_SP(
P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE,
P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DETALLE_FACTURA_TB(ID_DETALLE, CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_FACTURA, ID_PRODUCTO, ID_ESTADO) 
   VALUES(P_ID_DETALLE, P_CANTIDAD, P_PRECIO_UNITARIO, P_TOTAL, P_ID_FACTURA, P_ID_PRODUCTO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DETALLE_FACTURA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_FACTURA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE,
    P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DETALLE_FACTURA_TB
    SET CANTIDAD = P_CANTIDAD,
            PRECIO_UNITARIO = P_PRECIO_UNITARIO,
            TOTAL = P_TOTAL,
            ID_FACTURA = P_ID_FACTURA,
            ID_PRODUCTO = P_ID_PRODUCTO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DETALLE = P_ID_DETALLE; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DETALLE_FACTURA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_FACTURA_SP(
    P_ID_DETALLE IN FIDE_DETALLE_FACTURA_TB.ID_DETALLE%TYPE
)IS
BEGIN
    UPDATE FIDE_DETALLE_FACTURA_TB
    SET ID_ESTADO = 2
    WHERE ID_DETALLE = P_ID_DETALLE;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DETALLE_FACTURA_SP;

END FIDE_PROYECTO_FINAL_PCK;