--Creacion de tablas

CREATE TABLE FIDE_ESTADOS_TB(
ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADOS_PK PRIMARY KEY,
NOMBRE_ESTADO VARCHAR2(100),
DESCRIPCION_ESTADO VARCHAR2(100)
);
/
CREATE TABLE FIDE_MARCAALIMENTO_TB(
ID_MARCAALIMENTO NUMBER CONSTRAINT FIDE_MARCAALIMENTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(100),
ID_ESTADO NUMBER,
FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
CREATE TABLE FIDE_GENERO_TB (
ID_GENERO   NUMBER,
GENERO      VARCHAR2(50) NOT NULL,
ID_ESTADO   NUMBER,
CONSTRAINT FIDE_GENERO_PK PRIMARY KEY (ID_GENERO),
CONSTRAINT FIDE_GENERO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_TIPO_TB (
ID_TIPO          NUMBER,
NOMBRE_TIPO      VARCHAR2(100) NOT NULL,
DESCRIPCION_TIPO VARCHAR2(200),
ID_ESTADO        NUMBER,
CONSTRAINT FIDE_TIPO_PK PRIMARY KEY (ID_TIPO),
CONSTRAINT FIDE_TIPO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_HABITAT_TB (
ID_HABITAT          NUMBER,
NOMBRE_HABITAT      VARCHAR2(100) NOT NULL,
DESCRIPCION_HABITAT VARCHAR2(200),
ID_ESTADO           NUMBER,
CONSTRAINT FIDE_HABITAT_PK PRIMARY KEY (ID_HABITAT),
CONSTRAINT FIDE_HABITAT_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_RUTINA_TB (
ID_RUTINA    NUMBER,
NOMBRE_RUTINA VARCHAR2(100) NOT NULL,
ID_ESTADO     NUMBER,
CONSTRAINT FIDE_RUTINA_PK PRIMARY KEY (ID_RUTINA),
CONSTRAINT FIDE_RUTINA_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_MARCA_ALIMENTO_TB (
ID_MARCA_ALIMENTO NUMBER,
NOMBRE            VARCHAR2(100) NOT NULL,
DESCRIPCION       VARCHAR2(200),
ID_ESTADO         NUMBER,
CONSTRAINT FIDE_MARCA_ALIMENTO_PK PRIMARY KEY (ID_MARCA_ALIMENTO),
CONSTRAINT FIDE_MARCA_ALIMENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);

CREATE TABLE FIDE_ALIMENTACION_TB (
ID_ALIMENTACION   NUMBER,
CANTIDAD          NUMBER,
HORARIO           VARCHAR2(50),
FRECUENCIA        VARCHAR2(50),
ID_MARCA_ALIMENTO NUMBER,
ID_ESTADO         NUMBER,
ID_RUTINA         NUMBER,
CONSTRAINT FIDE_ALIMENTACION_PK PRIMARY KEY (ID_ALIMENTACION),
CONSTRAINT FIDE_ALIMENTACION_MARCA_FK FOREIGN KEY (ID_MARCA_ALIMENTO) REFERENCES FIDE_MARCA_ALIMENTO_TB(ID_MARCA_ALIMENTO),
CONSTRAINT FIDE_ALIMENTACION_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT FIDE_ALIMENTACION_RUTINA_FK FOREIGN KEY (ID_RUTINA) REFERENCES FIDE_RUTINA_TB(ID_RUTINA)
);

CREATE TABLE FIDE_ANIMAL_TB (
ID_ANIMAL       NUMBER,
NOMBRE_ANIMAL   VARCHAR2(100) NOT NULL,
FECHA_INGRESO   DATE,
EDAD            NUMBER,
PESO            NUMBER,
OBSERVACION     VARCHAR2(300),
ID_GENERO       NUMBER,
ID_TIPO         NUMBER,
ID_HABITAT      NUMBER,
ID_ESTADO       NUMBER,
ID_ALIMENTACION NUMBER,
CONSTRAINT FIDE_ANIMAL_PK PRIMARY KEY (ID_ANIMAL),
CONSTRAINT FIDE_ANIMAL_GENERO_FK FOREIGN KEY (ID_GENERO) REFERENCES FIDE_GENERO_TB(ID_GENERO),
CONSTRAINT FIDE_ANIMAL_TIPO_FK FOREIGN KEY (ID_TIPO) REFERENCES FIDE_TIPO_TB(ID_TIPO),
CONSTRAINT FIDE_ANIMAL_HABITAT_FK FOREIGN KEY (ID_HABITAT) REFERENCES FIDE_HABITAT_TB(ID_HABITAT),
CONSTRAINT FIDE_ANIMAL_ESTADO_FK FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT FIDE_ANIMAL_ALIMENTACION_FK FOREIGN KEY (ID_ALIMENTACION) REFERENCES FIDE_ALIMENTACION_TB(ID_ALIMENTACION)
);


