--Creacion de tablas
CREATE TABLE FIDE_ESTADOS_TB(
        ID_ESTADO NUMBER,
        NOMBRE_ESTADO VARCHAR2(100),
        DESCRIPCION_ESTADO VARCHAR2(100),
        
        -- Clave primaria
        CONSTRAINT FIDE_ESTADOS_PK PRIMARY KEY (ID_ESTADO)

);
/

CREATE TABLE FIDE_GENERO_TB (
        ID_GENERO   NUMBER,
        GENERO      VARCHAR2(50) NOT NULL,
        ID_ESTADO   NUMBER,

        -- Clave primaria
        CONSTRAINT FIDE_GENERO_PK PRIMARY KEY (ID_GENERO),
        
        -- Claves foráneas
        CONSTRAINT FIDE_GENERO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_TIPO_TB (
        ID_TIPO          NUMBER,
        NOMBRE_TIPO      VARCHAR2(100) NOT NULL,
        DESCRIPCION_TIPO VARCHAR2(200),
        ID_ESTADO        NUMBER,

        -- Clave primaria
        CONSTRAINT FIDE_TIPO_PK PRIMARY KEY (ID_TIPO),
        
        -- Claves foráneas
        CONSTRAINT FIDE_TIPO_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_HABITAT_TB (
        ID_HABITAT          NUMBER,
        NOMBRE_HABITAT      VARCHAR2(100) NOT NULL,
        DESCRIPCION_HABITAT VARCHAR2(200),
        ID_ESTADO           NUMBER,

        -- Clave primaria
         CONSTRAINT FIDE_HABITAT_PK PRIMARY KEY (ID_HABITAT),
            
            
        -- Claves foráneas 
        CONSTRAINT FIDE_HABITAT_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_RUTINA_TB (
        ID_RUTINA    NUMBER,
        NOMBRE_RUTINA VARCHAR2(100) NOT NULL,
        ID_ESTADO     NUMBER,
    
        -- Clave primaria
        CONSTRAINT FIDE_RUTINA_PK PRIMARY KEY (ID_RUTINA),
            
            
        -- Claves foráneas
        CONSTRAINT FIDE_RUTINA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_MARCAALIMENTO_TB (
        ID_MARCAALIMENTO NUMBER,
        NOMBRE            VARCHAR2(100) NOT NULL,
        DESCRIPCION       VARCHAR2(200),
        ID_ESTADO         NUMBER,
        
        -- Clave primaria
        CONSTRAINT FIDE_MARCA_ALIMENTO_PK PRIMARY KEY (ID_MARCA_ALIMENTO),
        
        -- Claves foráneas
        CONSTRAINT FIDE_MARCA_ALIMENTO_ESTADO_FK FOREIGN KEY (ID_ESTADO) 
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_ALIMENTACION_TB (
        ID_ALIMENTACION   NUMBER,
        CANTIDAD          NUMBER,
        HORARIO           VARCHAR2(50),
        FRECUENCIA        VARCHAR2(50),
        ID_MARCA_ALIMENTO NUMBER,
        ID_ESTADO         NUMBER,
        ID_RUTINA         NUMBER,
        
        -- Clave primaria
        CONSTRAINT FIDE_ALIMENTACION_PK PRIMARY KEY (ID_ALIMENTACION),
        
        -- Claves foráneas
        CONSTRAINT FIDE_ALIMENTACION_MARCA_FK FOREIGN KEY (ID_MARCA_ALIMENTO) 
        REFERENCES FIDE_MARCA_ALIMENTO_TB(ID_MARCA_ALIMENTO),
        
        CONSTRAINT FIDE_ALIMENTACION_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
        
        CONSTRAINT FIDE_ALIMENTACION_RUTINA_FK FOREIGN KEY (ID_RUTINA) 
        REFERENCES FIDE_RUTINA_TB(ID_RUTINA)
);
/

CREATE TABLE FIDE_ANIMAL_TB (
        ID_ANIMAL       NUMBER,
        NOMBRE_ANIMAL   VARCHAR2(100) NOT NULL,
        FECHA_INGRESO   DATE,
        EDAD            NUMBER,
        PESO            NUMBER,
        OBSERVACION     VARCHAR2(300),
        ID_GENERO       NUMBER,
        ID_TIPO         NUMBER,
        ID_HABITAT      NUMBER,
        ID_ESTADO       NUMBER,
        ID_ALIMENTACION NUMBER,
        
        -- Clave primaria
        CONSTRAINT FIDE_ANIMAL_PK PRIMARY KEY (ID_ANIMAL),
        
        -- Claves foráneas
        CONSTRAINT FIDE_ANIMAL_GENERO_FK FOREIGN KEY (ID_GENERO) 
        REFERENCES FIDE_GENERO_TB(ID_GENERO),
        
        CONSTRAINT FIDE_ANIMAL_TIPO_FK FOREIGN KEY (ID_TIPO) 
        REFERENCES FIDE_TIPO_TB(ID_TIPO),
        
        CONSTRAINT FIDE_ANIMAL_HABITAT_FK FOREIGN KEY (ID_HABITAT) 
        REFERENCES FIDE_HABITAT_TB(ID_HABITAT),
        
        CONSTRAINT FIDE_ANIMAL_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
        
        CONSTRAINT FIDE_ANIMAL_ALIMENTACION_FK FOREIGN KEY (ID_ALIMENTACION) 
        REFERENCES FIDE_ALIMENTACION_TB(ID_ALIMENTACION)
);
/

CREATE TABLE FIDE_ROL_TB (
    ID_ROL                NUMBER,
    NOMBRE_ROL    VARCHAR2(100),
    DESCRIPCION     VARCHAR2(100),
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_ROL_PK PRIMARY KEY (ID_ROL),
 
    -- Claves foráneas
    CONSTRAINT FIDE_ROL_ESTADO_FK FOREIGN KEY (ID_ESTADO)
     REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_USUARIO_TB (
    ID_USUARIO                NUMBER,
    NOMBRE                      VARCHAR2(100),
    FECHA_REGISTRO       DATE,
    TELEFONO                    VARCHAR2(20),
    CORREO                       VARCHAR2(100),
    ID_ESTADO                   NUMBER,
    ID_ROL                          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_USUARIO_PK PRIMARY KEY (ID_USUARIO),
 
    -- Claves foráneas
    CONSTRAINT FIDE_USUARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
    
    CONSTRAINT FIDE_USUARIO_ROL_FK FOREIGN KEY (ID_ROL)
    REFERENCES FIDE_ROL_TB(ID_ROL)    
);
/

CREATE TABLE FIDE_HORARIO_TB (
    ID_HORARIO     NUMBER,
    DIA                     VARCHAR2(10),
    HORA_INICIO    DATE,
    HORA_FINAL     DATE,
    ID_USUARIO       NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_HORARIO_PK PRIMARY KEY (ID_HORARIO),
 
    -- Claves foráneas
     CONSTRAINT FIDE_HORARIO_USUARIO_FK FOREIGN KEY (ID_USUARIO)
     REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
     
    CONSTRAINT FIDE_HORARIO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
     REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_ENTREGA_TB (
    ID_ENTREGA       NUMBER,
    FECHA                  DATE,
    ID_DIRECCION    NUMBER,
    ID_USUARIO        NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_ENTREGA_PK PRIMARY KEY (ID_ENTREGA),
 
    -- Claves foráneas
    CONSTRAINT FIDE_ENTREGA_DIRECCION_FK FOREIGN KEY (ID_DIRECCION)
    REFERENCES FIDE_DIRECCION_TB(ID_DIRECCION),
        
    CONSTRAINT FIDE_ENTREGA_USUARIO_FK FOREIGN KEY (ID_USUARIO)
    REFERENCES FIDE_USUARIO_TB(ID_USUARIO),
        
    CONSTRAINT FIDE_ENTREGA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_DETALLE_ENTREGA_TB (
    ID_DETALLE         NUMBER, 
    DESCRIPCION     VARCHAR2(100),
    CANTIDAD           NUMBER,
    ID_ENTREGA        NUMBER,
    ID_ESTADO          NUMBER,
 
    -- Clave primaria
    CONSTRAINT FIDE_DETALLE_ENTREGA_PK PRIMARY KEY (ID_DETALLE),
 
    -- Claves foráneas
    CONSTRAINT FIDE_DETALLE_ENTREGA_FK FOREIGN KEY (ID_ENTREGA)
    REFERENCES FIDE_ENTREGA_TB(ID_ENTREGA),
    
    CONSTRAINT FIDE_DETALLE_ESTADO_FK FOREIGN KEY (ID_ESTADO)
    REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    ID_DETALLE NUMBER,
    CANTIDAD NUMBER,
    PRECIO_UNITARIO NUMBER(10,2),
    TOTAL NUMBER(10,2),
    ID_FACTURA NUMBER,
    ID_PRODUCTO NUMBER,
    ID_ESTADO NUMBER,

    -- Clave primaria
    CONSTRAINT FIDE_DETALLE_FACTURA_PK PRIMARY KEY (ID_DETALLE),

    -- Claves foráneas
    CONSTRAINT FIDE_DETALLE_FACTURA_FACTURA_FK FOREIGN KEY (ID_FACTURA)
        REFERENCES FIDE_FACTURA_TB(ID_FACTURA),

    CONSTRAINT FIDE_DETALLE_FACTURA_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO)
        REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO),

    CONSTRAINT FIDE_DETALLE_FACTURA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_FACTURA_TB (
    ID_FACTURA NUMBER,
    FECHA_REGISTRO DATE,
    MONTO_TOTAL NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    IVA NUMBER(10,2),
    DESCUENTO NUMBER(10,2),
    ID_USUARIO NUMBER,
    ID_METODO_PAGO NUMBER,
    ID_ESTADO NUMBER,

    -- Clave primaria
    CONSTRAINT FIDE_FACTURA_PK PRIMARY KEY (ID_FACTURA),

    -- Claves foráneas
    CONSTRAINT FIDE_FACTURA_USUARIO_FK FOREIGN KEY (ID_USUARIO)
        REFERENCES FIDE_USUARIO_TB(ID_USUARIO),

    CONSTRAINT FIDE_FACTURA_METODOPAGO_FK FOREIGN KEY (ID_METODO_PAGO)
        REFERENCES FIDE_METODO_PAGO_TB(ID_METODO_PAGO),

    CONSTRAINT FIDE_FACTURA_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/

CREATE TABLE FIDE_METODO_PAGO_TB (
    ID_METODO_PAGO NUMBER,
    NOMBRE_METODO_PAGO VARCHAR2(50),
    ID_ESTADO NUMBER,
    
    -- Clave primaria
    CONSTRAINT FIDE_METODO_PAGO_PK PRIMARY KEY (ID_METODO_PAGO),

    -- Claves foráneas
    CONSTRAINT FIDE_METODO_PAGO_ESTADO_FK FOREIGN KEY (ID_ESTADO)
        REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/



