--Creacion de tablas

CREATE TABLE FIDE_ESTADOS_TB(
ID_ESTADO NUMBER CONSTRAINT FIDE_ESTADOS_PK PRIMARY KEY,
NOMBRE_ESTADO VARCHAR2(100),
DESCRIPCION_ESTADO VARCHAR2(100)
);
/
CREATE TABLE FIDE_MARCAALIMENTO_TB(
ID_MARCAALIMENTO NUMBER CONSTRAINT FIDE_MARCAALIMENTO_PK PRIMARY KEY,
NOMBRE VARCHAR2(100),
DESCRIPCION VARCHAR2(100),
ID_ESTADO NUMBER,
FOREIGN KEY (ID_ESTADO) REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
);
/
