create or replace PACKAGE FIDE_PROYECTO_FINAL_PCK AS

PROCEDURE FIDE_INSERTAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
);

--TABLA DE GENERO
--INSERTAR
PROCEDURE FIDE_INSERTAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE
);

--TABLA DE TIPO
--INSERTAR
PROCEDURE FIDE_INSERTAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE
);

--TABLA DE HABITAT
--INSERTAR
PROCEDURE FIDE_INSERTAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE
);

--TABLA DE RUTINA
--INSERTAR
PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
);

--TABLA DE MARCA_ALIMENTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE
);




--TABLA DE ALIMENTACION
--INSERTAR
PROCEDURE FIDE_INSERTAR_ALIMENTACION_SP(
P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
); 

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ALIMENTACION_SP(
    P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
    P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
    P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
    P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
    P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
    P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
);

---ELIMINAR
PROCEDURE FIDE_ELIMINAR_ALIMENTACION_SP(
  P_HORARIO   IN VARCHAR2,
  P_ID_RUTINA IN NUMBER
);


--TABLA DE ANIMAL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ANIMAL_SP(
P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE
);


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
    P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
    P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
    P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
    P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
    P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
    P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
    P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
    P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
    P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE
  
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE
);








--TABLA DE USUARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_USUARIO_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
    P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
    P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
    P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
    P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE
);


--TABLA DE HORARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_HORARIO_SP(
P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
    P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
    P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
    P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
    P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE
);

--TABLA DE PAIS
--INSERTAR
PROCEDURE FIDE_INSERTAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
);

--TABLA DE PROVINCIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
);

--TABLA DE CANTON
--INSERTAR
PROCEDURE FIDE_INSERTAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
);

--TABLA DE DISTRITO
--INSERTAR
PROCEDURE FIDE_INSERTAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
);

--TABLA DIRECCION
--INSERTAR
PROCEDURE FIDE_INSERTAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DIRECCION_SP(
    P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
);

--TABLA DE EMPRESA
--INSERTAR
PROCEDURE FIDE_INSERTAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE
);

--TABLA DE ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_ENTREGA_SP(
P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ENTREGA_SP(
   P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
    P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
    P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ENTREGA_SP(
    P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE
);

--TABLA DE DETALLE_ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_ENTREGA_SP(
P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_ENTREGA_SP(
    P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
    P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
    P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
-- ELIMINAR DETALLE ENTREGA
PROCEDURE FIDE_ELIMINAR_DETALLE_ENTREGA_SP(
  P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE
);





--TABLA DE CATEGORIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
);

--TABLA DE UNIDAD_MEDIDA
--INSERTAR
PROCEDURE FIDE_INSERTAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE
);

--TABLA DE PRODUCTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_PRODUCTO_SP(
P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PRODUCTO_SP(
   P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
    P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
    P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PRODUCTO_SP(
    P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
);



--TABLA DE INVENTARIO
-- INSERTAR
PROCEDURE FIDE_INSERTAR_INVENTARIO_SP(
    P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
);

-- MODIFICAR
PROCEDURE FIDE_MODIFICAR_INVENTARIO_SP(
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
    P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
);

-- ELIMINAR
PROCEDURE FIDE_ELIMINAR_INVENTARIO_SP(
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE
);


--TABLA DE METODO_PAGO
--INSERTAR
PROCEDURE FIDE_INSERTAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
);

--TABLA DE FACTURA
--INSERTAR 
PROCEDURE FIDE_INSERTAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
);

--ELIMINAR
PROCEDURE FIDE_ELIMINAR_FACTURA_SP(
    P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
);

--TABLA DETALLE_FACTURA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_FACTURA_SP(
P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);

--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_FACTURA_SP(
    P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
);

---ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_FACTURA_SP(
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE
);



---FUNCIONES

FUNCTION FIDE_USUARIOS_POR_ROL_FN(P_ROL IN NUMBER) 
RETURN VARCHAR2;

FUNCTION FIDE_CONTAR_PRODUCTOS_POR_CATEGORIA_FN(P_CATEGORIA IN NUMBER) 
RETURN NUMBER;

FUNCTION FIDE_PESO_PROMEDIO_POR_HABITAT_FN(P_HABITAT IN NUMBER) 
RETURN NUMBER;

FUNCTION FIDE_OBTENER_DIRECCION_USUARIO_FN(P_ID_USUARIO IN NUMBER) RETURN VARCHAR2;


FUNCTION FIDE_TOTAL_FACTURAS_USUARIO_FN(P_USUARIO IN NUMBER) 
RETURN NUMBER;

FUNCTION FIDE_DETALLE_FACTURA_CADENA_FN(P_FACTURA IN NUMBER) 
RETURN VARCHAR2;

FUNCTION FIDE_CANTIDAD_TOTAL_INVENTARIO_FN(P_PRODUCTO IN NUMBER) 
RETURN NUMBER;



END FIDE_PROYECTO_FINAL_PCK;






create or replace PACKAGE BODY FIDE_PROYECTO_FINAL_PCK AS

---INSERTAR
PROCEDURE FIDE_INSERTAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION_ESTADO)
   VALUES(P_ID_ESTADO, P_NOMBRE_ESTADO, P_DESCRIPCION_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ESTADO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO,
            DESCRIPCION_ESTADO = P_DESCRIPCION_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ESTADO_SP;


--TABLA DE GENERO
--INSERTAR
PROCEDURE FIDE_INSERTAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_GENERO_TB (ID_GENERO, GENERO, ID_ESTADO)
   VALUES(P_ID_GENERO, P_GENERO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_GENERO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET GENERO = P_GENERO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_GENERO_SP;




--ELIMINAR
PROCEDURE FIDE_ELIMINAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET ID_ESTADO = 2
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_GENERO_SP;


--TABLA DE TIPO
--INSERTAR
PROCEDURE FIDE_INSERTAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_TIPO_TB (ID_TIPO, NOMBRE_TIPO, DESCRIPCION_TIPO, ID_ESTADO)
   VALUES(P_ID_TIPO, P_NOMBRE_TIPO, P_DESCRIPCION_TIPO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_TIPO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET NOMBRE_TIPO = P_NOMBRE_TIPO,
            DESCRIPCION_TIPO = P_DESCRIPCION_TIPO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_TIPO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_TIPO_SP;


--TABLA DE HABITAT
--INSERTAR
PROCEDURE FIDE_INSERTAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_HABITAT_TB (ID_HABITAT, NOMBRE_HABITAT, DESCRIPCION_HABITAT, ID_ESTADO)
   VALUES(P_ID_HABITAT, P_NOMBRE_HABITAT, P_DESCRIPCION_HABITAT, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_HABITAT_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET NOMBRE_HABITAT = P_NOMBRE_HABITAT,
            DESCRIPCION_HABITAT = P_DESCRIPCION_HABITAT,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_HABITAT_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET ID_ESTADO = 2
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_HABITAT_SP;




--TABLA DE RUTINA
--INSERTAR
PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_RUTINA_TB (ID_RUTINA, NOMBRE_RUTINA, ID_ESTADO)
   VALUES(P_ID_RUTINA, P_NOMBRE_RUTINA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_RUTINA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET NOMBRE_RUTINA = P_NOMBRE_RUTINA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_RUTINA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET ID_ESTADO = 2
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_RUTINA_SP;


--TABLA DE MARCA_ALIMENTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_MARCA_ALIMENTO_TB (ID_MARCA_ALIMENTO, NOMBRE, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_MARCA_ALIMENTO, P_NOMBRE, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_MARCA_ALIMENTO_SP;




--MODIFICAR
PROCEDURE FIDE_MODIFICAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET NOMBRE = P_NOMBRE,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_MARCA_ALIMENTO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET ID_ESTADO = 2
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_MARCA_ALIMENTO_SP;


--INSERTAR
PROCEDURE FIDE_INSERTAR_ALIMENTACION_SP(
P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ALIMENTACION_TB (CANTIDAD, HORARIO, FRECUENCIA, ID_MARCA_ALIMENTO, ID_ESTADO, ID_RUTINA) 
   VALUES(P_CANTIDAD, P_HORARIO, P_FRECUENCIA, P_ID_MARCA_ALIMENTO, P_ID_ESTADO, P_ID_RUTINA);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ALIMENTACION_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ALIMENTACION_SP(
    P_CANTIDAD           IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
    P_HORARIO            IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
    P_FRECUENCIA         IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
    P_ID_MARCA_ALIMENTO  IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
    P_ID_ESTADO          IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
    P_ID_RUTINA          IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
    UPDATE FIDE_ALIMENTACION_TB
    SET CANTIDAD           = P_CANTIDAD,
        FRECUENCIA         = P_FRECUENCIA,
        ID_MARCA_ALIMENTO  = P_ID_MARCA_ALIMENTO,
        ID_ESTADO          = P_ID_ESTADO
    WHERE HORARIO = P_HORARIO
      AND ID_RUTINA = P_ID_RUTINA;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_MODIFICAR_ALIMENTACION_SP;



--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ALIMENTACION_SP(
  P_HORARIO   IN VARCHAR2,
  P_ID_RUTINA IN NUMBER
) IS
BEGIN
  DELETE FROM FIDE_ALIMENTACION_TB
  WHERE HORARIO = P_HORARIO
    AND ID_RUTINA = P_ID_RUTINA;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END  FIDE_ELIMINAR_ALIMENTACION_SP;


--TABLA DE ANIMAL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ANIMAL_SP(
P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ANIMAL_TB (ID_ANIMAL, NOMBRE_ANIMAL, FECHA_INGRESO, EDAD, PESO, OBSERVACION, ID_GENERO, ID_TIPO, ID_HABITAT, ID_ESTADO) 
   VALUES(P_ID_ANIMAL, P_NOMBRE_ANIMAL, P_FECHA_INGRESO, P_EDAD, P_PESO, P_OBSERVACION, P_ID_GENERO, P_ID_TIPO, P_ID_HABITAT, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ANIMAL_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ANIMAL_SP(
  P_ID_ANIMAL      IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
  P_NOMBRE_ANIMAL  IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
  P_FECHA_INGRESO  IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
  P_EDAD           IN FIDE_ANIMAL_TB.EDAD%TYPE,
  P_PESO           IN FIDE_ANIMAL_TB.PESO%TYPE,
  P_OBSERVACION    IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
  P_ID_GENERO      IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
  P_ID_TIPO        IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
  P_ID_HABITAT     IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
  P_ID_ESTADO      IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE 
) IS
BEGIN
  UPDATE FIDE_ANIMAL_TB
  SET NOMBRE_ANIMAL   = P_NOMBRE_ANIMAL,
      FECHA_INGRESO   = P_FECHA_INGRESO,
      EDAD            = P_EDAD,
      PESO            = P_PESO,
      OBSERVACION     = P_OBSERVACION,
      ID_GENERO       = P_ID_GENERO,
      ID_TIPO         = P_ID_TIPO,
      ID_HABITAT      = P_ID_HABITAT,
      ID_ESTADO       = P_ID_ESTADO 
  WHERE ID_ANIMAL = P_ID_ANIMAL;

  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_MODIFICAR_ANIMAL_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE
)IS
BEGIN
    UPDATE FIDE_ANIMAL_TB
    SET ID_ESTADO = 2
    WHERE ID_ANIMAL = P_ID_ANIMAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ANIMAL_SP;



--TABLA DE ROL
--INSERTAR
PROCEDURE FIDE_INSERTAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_ROL, P_NOMBRE_ROL, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ROL_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET NOMBRE_ROL = P_NOMBRE_ROL,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ROL_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET ID_ESTADO = 2
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ROL_SP;



--TABLA DE USUARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_USUARIO_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
   INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE, FECHA_REGISTRO, TELEFONO, CORREO, ID_ESTADO, ID_ROL) 
   VALUES(P_ID_USUARIO, P_NOMBRE, P_FECHA_REGISTRO, P_TELEFONO, P_CORREO, P_ID_ESTADO, P_ID_ROL);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_USUARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
    P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
    P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
    P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
    P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET NOMBRE = P_NOMBRE,
            FECHA_REGISTRO = P_FECHA_REGISTRO,
            TELEFONO = P_TELEFONO,
            CORREO = P_CORREO,
            ID_ESTADO = P_ID_ESTADO,
            ID_ROL = P_ID_ROL
    WHERE ID_USUARIO = P_ID_USUARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_USUARIO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_USUARIO = P_ID_USUARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_USUARIO_SP;


--TABLA DE HORARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_HORARIO_SP(
P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_HORARIO_TB (ID_HORARIO, DIA, HORA_INICIO, HORA_FINAL, ID_USUARIO, ID_ESTADO) 
   VALUES(P_ID_HORARIO, P_DIA, P_HORA_INICIO, P_HORA_FINAL, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_HORARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE,
    P_DIA IN FIDE_HORARIO_TB.DIA%TYPE,
    P_HORA_INICIO IN FIDE_HORARIO_TB.HORA_INICIO%TYPE,
    P_HORA_FINAL IN FIDE_HORARIO_TB.HORA_FINAL%TYPE,
    P_ID_USUARIO IN FIDE_HORARIO_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_HORARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_HORARIO_TB
    SET DIA = P_DIA,
            HORA_INICIO = P_HORA_INICIO,
            HORA_FINAL = P_HORA_FINAL,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_HORARIO = P_ID_HORARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_HORARIO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_HORARIO_SP(
    P_ID_HORARIO IN FIDE_HORARIO_TB.ID_HORARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_HORARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_HORARIO = P_ID_HORARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_HORARIO_SP;


--TABLA DE PAIS
--INSERTAR
PROCEDURE FIDE_INSERTAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PAIS_TB (ID_PAIS, NOMBRE_PAIS, ID_ESTADO)
   VALUES(P_ID_PAIS, P_NOMBRE_PAIS, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PAIS_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET NOMBRE_PAIS = P_NOMBRE_PAIS,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PAIS_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET ID_ESTADO = 2
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PAIS_SP;


--TABLA DE PROVINCIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA, ID_ESTADO)
   VALUES(P_ID_PROVINCIA, P_NOMBRE_PROVINCIA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PROVINCIA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET NOMBRE_PROVINCIA = P_NOMBRE_PROVINCIA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PROVINCIA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET ID_ESTADO = 2
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PROVINCIA_SP;


--TABLA DE CANTON
--INSERTAR
PROCEDURE FIDE_INSERTAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_ESTADO)
   VALUES(P_ID_CANTON, P_NOMBRE_CANTON, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_CANTON_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET NOMBRE_CANTON = P_NOMBRE_CANTON,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_CANTON_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET ID_ESTADO = 2
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_CANTON_SP;


--TABLA DE DISTRITO
--INSERTAR
PROCEDURE FIDE_INSERTAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_ESTADO)
   VALUES(P_ID_DISTRITO, P_NOMBRE_DISTRITO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DISTRITO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET NOMBRE_DISTRITO = P_NOMBRE_DISTRITO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DISTRITO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET ID_ESTADO = 2
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DISTRITO_SP;


--TABLA DIRECCION
--TABLA DIRECCION
--INSERTAR
PROCEDURE FIDE_INSERTAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DIRECCION_TB(id_DIRECCION, DETALLE_DIRECCION, ID_DISTRITO, ID_CANTON, ID_PROVINCIA, ID_PAIS, ID_ESTADO) 
   VALUES(P_ID_DIRECCION, P_DETALLE_DIRECCION, P_ID_DISTRITO, P_ID_CANTON, P_ID_PROVINCIA, P_ID_PAIS, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DIRECCION_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DIRECCION_SP(
P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
P_DETALLE_DIRECCION IN FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE,
P_ID_DISTRITO IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
P_ID_CANTON IN FIDE_DIRECCION_TB.ID_CANTON%TYPE,
P_ID_PROVINCIA IN FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE,
P_ID_PAIS IN FIDE_DIRECCION_TB.ID_PAIS%TYPE,
P_ID_ESTADO IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DIRECCION_TB
    SET DETALLE_DIRECCION = P_DETALLE_DIRECCION,
            ID_DISTRITO = P_ID_DISTRITO,
            ID_CANTON = P_ID_CANTON,
            ID_PROVINCIA = P_ID_PROVINCIA,
            ID_PAIS = P_ID_PAIS,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DIRECCION = P_ID_DIRECCION; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DIRECCION_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_DIRECCION_SP(
    P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
)IS
BEGIN
    UPDATE FIDE_DIRECCION_TB
    SET ID_ESTADO = 2
    WHERE ID_DIRECCION = P_ID_DIRECCION;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DIRECCION_SP;



--TABLA DE EMPRESA
--INSERTAR
PROCEDURE FIDE_INSERTAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_EMPRESA_TB(ID_EMPRESA, NOMBRE_EMPRESA, TELEFONO, CORREO, ID_DIRECCION, ID_ESTADO) 
   VALUES(P_ID_EMPRESA, P_NOMBRE_EMPRESA, P_TELEFONO, P_CORREO, P_ID_DIRECCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_EMPRESA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE,
    P_NOMBRE_EMPRESA IN FIDE_EMPRESA_TB.NOMBRE_EMPRESA%TYPE,
    P_TELEFONO IN FIDE_EMPRESA_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_EMPRESA_TB.CORREO%TYPE,
    P_ID_DIRECCION IN FIDE_EMPRESA_TB.ID_DIRECCION%TYPE,
    P_ID_ESTADO IN FIDE_EMPRESA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_EMPRESA_TB
    SET NOMBRE_EMPRESA = P_NOMBRE_EMPRESA,
            TELEFONO = P_TELEFONO,
            CORREO = P_CORREO,
            ID_DIRECCION = P_ID_DIRECCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_EMPRESA = P_ID_EMPRESA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_EMPRESA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_EMPRESA_SP(
    P_ID_EMPRESA IN FIDE_EMPRESA_TB.ID_EMPRESA%TYPE
)IS
BEGIN
    UPDATE FIDE_EMPRESA_TB
    SET ID_ESTADO = 2
    WHERE ID_EMPRESA = P_ID_EMPRESA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_EMPRESA_SP;




--TABLA DE ENTREGA
--INSERTAR
PROCEDURE FIDE_INSERTAR_ENTREGA_SP(
P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ENTREGA_TB(ID_ENTREGA, FECHA, ID_DIRECCION, ID_USUARIO,ID_ESTADO) 
   VALUES(P_ID_ENTREGA, P_FECHA, P_ID_DIRECCION, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ENTREGA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_ENTREGA_SP(
   P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE,
    P_FECHA IN FIDE_ENTREGA_TB.FECHA%TYPE,
    P_ID_DIRECCION IN FIDE_ENTREGA_TB.ID_DIRECCION%TYPE,
    P_ID_USUARIO IN FIDE_ENTREGA_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_ENTREGA_TB
    SET FECHA = P_FECHA,
            ID_DIRECCION = P_ID_DIRECCION,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_ENTREGA = P_ID_ENTREGA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ENTREGA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_ENTREGA_SP(
    P_ID_ENTREGA IN FIDE_ENTREGA_TB.ID_ENTREGA%TYPE
)IS
BEGIN
    UPDATE FIDE_ENTREGA_TB
    SET ID_ESTADO = 2
    WHERE ID_ENTREGA = P_ID_ENTREGA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ENTREGA_SP;


--TABLA DE DETALLE_ENTREGA
-- INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_ENTREGA_SP(
  P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
  P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
  P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
  P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
  INSERT INTO FIDE_DETALLE_ENTREGA_TB (DESCRIPCION, CANTIDAD, ID_ENTREGA, ID_ESTADO)
  VALUES (P_DESCRIPCION, P_CANTIDAD, P_ID_ENTREGA, P_ID_ESTADO);
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_INSERTAR_DETALLE_ENTREGA_SP;


-- MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_ENTREGA_SP(
  P_DESCRIPCION IN FIDE_DETALLE_ENTREGA_TB.DESCRIPCION%TYPE,
  P_CANTIDAD IN FIDE_DETALLE_ENTREGA_TB.CANTIDAD%TYPE,
  P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE,
  P_ID_ESTADO IN FIDE_DETALLE_ENTREGA_TB.ID_ESTADO%TYPE
) IS
BEGIN
  UPDATE FIDE_DETALLE_ENTREGA_TB
  SET DESCRIPCION = P_DESCRIPCION,
      CANTIDAD = P_CANTIDAD,
      ID_ESTADO = P_ID_ESTADO
  WHERE ID_ENTREGA = P_ID_ENTREGA;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_MODIFICAR_DETALLE_ENTREGA_SP;


-- ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_ENTREGA_SP(
  P_ID_ENTREGA IN FIDE_DETALLE_ENTREGA_TB.ID_ENTREGA%TYPE
) IS
BEGIN
  UPDATE FIDE_DETALLE_ENTREGA_TB
  SET ID_ESTADO = 2
  WHERE ID_ENTREGA = P_ID_ENTREGA;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_ELIMINAR_DETALLE_ENTREGA_SP;


--TABLA DE CATEGORIA
--INSERTAR
PROCEDURE FIDE_INSERTAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_CATEGORIA_TB (ID_CATEGORIA, NOMBRE_CATEGORIA, ID_ESTADO)
   VALUES(P_ID_CATEGORIA, P_NOMBRE_CATEGORIA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_CATEGORIA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
P_NOMBRE_CATEGORIA IN FIDE_CATEGORIA_TB.NOMBRE_CATEGORIA%TYPE, 
P_ID_ESTADO IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET NOMBRE_CATEGORIA = P_NOMBRE_CATEGORIA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_CATEGORIA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_CATEGORIA_SP(
P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
)IS
    BEGIN
    UPDATE FIDE_CATEGORIA_TB
    SET ID_ESTADO = 2
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_CATEGORIA_SP;


--TABLA DE UNIDAD_MEDIDA
--INSERTAR
PROCEDURE FIDE_INSERTAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_UNIDAD_MEDIDA_TB (ID_UNIDAD_MEDIDA, NOMBRE_UNIDAD_MEDIDA, ID_ESTADO)
   VALUES(P_ID_UNIDAD_MEDIDA, P_NOMBRE_UNIDAD_MEDIDA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_UNIDAD_MEDIDA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE,
P_NOMBRE_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.NOMBRE_UNIDAD_MEDIDA%TYPE, 
P_ID_ESTADO IN FIDE_UNIDAD_MEDIDA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_UNIDAD_MEDIDA_TB
    SET NOMBRE_UNIDAD_MEDIDA = P_NOMBRE_UNIDAD_MEDIDA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_UNIDAD_MEDIDA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_UNIDAD_MEDIDA_SP(
P_ID_UNIDAD_MEDIDA IN FIDE_UNIDAD_MEDIDA_TB.ID_UNIDAD_MEDIDA%TYPE
)IS
    BEGIN
    UPDATE FIDE_UNIDAD_MEDIDA_TB
    SET ID_ESTADO = 2
    WHERE ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_UNIDAD_MEDIDA_SP;


--TABLA DE PRODUCTO
--INSERTAR
PROCEDURE FIDE_INSERTAR_PRODUCTO_SP(
P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PRODUCTO_TB(ID_PRODUCTO, NOMBRE, ID_CATEGORIA, ID_UNIDAD_MEDIDA,ID_ESTADO) 
   VALUES(P_ID_PRODUCTO, P_NOMBRE, P_ID_CATEGORIA, P_ID_UNIDAD_MEDIDA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PRODUCTO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_PRODUCTO_SP(
   P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
    P_NOMBRE IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
    P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
    P_ID_UNIDAD_MEDIDA IN FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE,
    P_ID_ESTADO IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_PRODUCTO_TB
    SET NOMBRE = P_NOMBRE,
            ID_CATEGORIA = P_ID_CATEGORIA,
            ID_UNIDAD_MEDIDA = P_ID_UNIDAD_MEDIDA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PRODUCTO = P_ID_PRODUCTO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PRODUCTO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_PRODUCTO_SP(
    P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
)IS
BEGIN
    UPDATE FIDE_PRODUCTO_TB
    SET ID_ESTADO = 2
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PRODUCTO_SP;


--TABLA DE INVENTARIO
--INSERTAR
PROCEDURE FIDE_INSERTAR_INVENTARIO_SP(
P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_INVENTARIO_TB(CANTIDAD, FECHA_INGRESO, ID_PRODUCTO,ID_ESTADO) 
   VALUES( P_CANTIDAD, P_FECHA_INGRESO, P_ID_PRODUCTO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_INVENTARIO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_INVENTARIO_SP(
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE,
    P_CANTIDAD IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
    P_ID_ESTADO IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB
    SET 
        CANTIDAD = P_CANTIDAD,
        ID_ESTADO = P_ID_ESTADO
    WHERE 
        ID_PRODUCTO = P_ID_PRODUCTO
        AND FECHA_INGRESO = P_FECHA_INGRESO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_MODIFICAR_INVENTARIO_SP;


----ELIMINAR
PROCEDURE FIDE_ELIMINAR_INVENTARIO_SP(
    P_ID_PRODUCTO IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
    P_FECHA_INGRESO IN FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE
) IS
BEGIN
    UPDATE FIDE_INVENTARIO_TB
    SET ID_ESTADO = 2
    WHERE 
        ID_PRODUCTO = P_ID_PRODUCTO
        AND FECHA_INGRESO = P_FECHA_INGRESO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_ELIMINAR_INVENTARIO_SP;



--TABLA DE METODO_PAGO
--INSERTAR
PROCEDURE FIDE_INSERTAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_METODO_PAGO_TB (ID_METODO_PAGO, NOMBRE_METODO_PAGO, ID_ESTADO)
   VALUES(P_ID_METODO_PAGO, P_NOMBRE_METODO_PAGO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_METODO_PAGO_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
P_NOMBRE_METODO_PAGO IN FIDE_METODO_PAGO_TB.NOMBRE_METODO_PAGO%TYPE, 
P_ID_ESTADO IN FIDE_METODO_PAGO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_METODO_PAGO_TB
    SET NOMBRE_METODO_PAGO = P_NOMBRE_METODO_PAGO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_METODO_PAGO_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_METODO_PAGO_SP(
P_ID_METODO_PAGO IN FIDE_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
)IS
    BEGIN
    UPDATE FIDE_METODO_PAGO_TB
    SET ID_ESTADO = 2
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_METODO_PAGO_SP;



--TABLA DE FACTURA
--INSERTAR 
PROCEDURE FIDE_INSERTAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_FACTURA_TB(ID_FACTURA, FECHA_REGISTRO, MONTO_TOTAL, SUBTOTAL, IVA, DESCUENTO, ID_USUARIO, ID_METODO_PAGO, ID_ESTADO) 
   VALUES(P_ID_FACTURA, P_FECHA_REGISTRO, P_MONTO_TOTAL, P_SUBTOTAL, P_IVA, P_DESCUENTO,  P_ID_USUARIO, P_ID_METODO_PAGO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_FACTURA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_FACTURA_SP(
P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
P_FECHA_REGISTRO IN FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE,
P_MONTO_TOTAL IN FIDE_FACTURA_TB.MONTO_TOTAL%TYPE,
P_SUBTOTAL IN FIDE_FACTURA_TB.SUBTOTAL%TYPE,
P_IVA IN FIDE_FACTURA_TB.IVA%TYPE,
P_DESCUENTO IN FIDE_FACTURA_TB.DESCUENTO%TYPE,
P_ID_USUARIO IN FIDE_FACTURA_TB.ID_USUARIO%TYPE,
P_ID_METODO_PAGO IN FIDE_FACTURA_TB.ID_METODO_PAGO%TYPE,
P_ID_ESTADO IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET FECHA_REGISTRO = P_FECHA_REGISTRO,
            MONTO_TOTAL = P_MONTO_TOTAL,
            SUBTOTAL = P_SUBTOTAL,
            IVA = P_IVA,
            DESCUENTO = P_DESCUENTO,
            ID_USUARIO = P_ID_USUARIO,
            ID_METODO_PAGO = P_ID_METODO_PAGO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_FACTURA_SP;


--ELIMINAR
PROCEDURE FIDE_ELIMINAR_FACTURA_SP(
    P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
)IS
BEGIN
    UPDATE FIDE_FACTURA_TB
    SET ID_ESTADO = 2
    WHERE ID_FACTURA = P_ID_FACTURA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_FACTURA_SP;


--TABLA DETALLE_FACTURA
--INSERTAR
PROCEDURE FIDE_INSERTAR_DETALLE_FACTURA_SP(
P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DETALLE_FACTURA_TB(CANTIDAD, PRECIO_UNITARIO, TOTAL, ID_FACTURA, ID_PRODUCTO, ID_ESTADO) 
   VALUES(P_CANTIDAD, P_PRECIO_UNITARIO, P_TOTAL, P_ID_FACTURA, P_ID_PRODUCTO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DETALLE_FACTURA_SP;


--MODIFICAR
PROCEDURE FIDE_MODIFICAR_DETALLE_FACTURA_SP(
    P_CANTIDAD IN FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE,
    P_PRECIO_UNITARIO IN FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE,
    P_TOTAL IN FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE,
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE,
    P_ID_ESTADO IN FIDE_DETALLE_FACTURA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE FIDE_DETALLE_FACTURA_TB
    SET CANTIDAD = P_CANTIDAD,
        PRECIO_UNITARIO = P_PRECIO_UNITARIO,
        TOTAL = P_TOTAL,
        ID_ESTADO = P_ID_ESTADO
    WHERE ID_FACTURA = P_ID_FACTURA
      AND ID_PRODUCTO = P_ID_PRODUCTO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_MODIFICAR_DETALLE_FACTURA_SP;


----ELIMINAR
PROCEDURE FIDE_ELIMINAR_DETALLE_FACTURA_SP(
    P_ID_FACTURA IN FIDE_DETALLE_FACTURA_TB.ID_FACTURA%TYPE,
    P_ID_PRODUCTO IN FIDE_DETALLE_FACTURA_TB.ID_PRODUCTO%TYPE
) IS
BEGIN
    DELETE FROM FIDE_DETALLE_FACTURA_TB
    WHERE ID_FACTURA = P_ID_FACTURA
      AND ID_PRODUCTO = P_ID_PRODUCTO;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_ELIMINAR_DETALLE_FACTURA_SP;

FUNCTION FIDE_USUARIOS_POR_ROL_FN(P_ROL IN NUMBER) 
RETURN VARCHAR2 IS
  CURSOR C_USUARIOS IS
    SELECT ID_USUARIO, NOMBRE, TELEFONO, CORREO
    FROM FIDE_USUARIO_TB
    WHERE ID_ROL = P_ROL;

  V_ID FIDE_USUARIO_TB.ID_USUARIO%TYPE;
  V_NOMBRE FIDE_USUARIO_TB.NOMBRE%TYPE;
  V_TELEFONO FIDE_USUARIO_TB.TELEFONO%TYPE;
  V_CORREO FIDE_USUARIO_TB.CORREO%TYPE;
  V_RESULTADO VARCHAR2(4000) := '';
BEGIN
  OPEN C_USUARIOS;
  LOOP
    FETCH C_USUARIOS INTO V_ID, V_NOMBRE, V_TELEFONO, V_CORREO;
    EXIT WHEN C_USUARIOS%NOTFOUND;

    V_RESULTADO := V_RESULTADO || 'ID: ' || V_ID || 
                   ' | NOMBRE: ' || V_NOMBRE || 
                   ' | TELEFONO: ' || V_TELEFONO || 
                   ' | CORREO: ' || V_CORREO || CHR(10);
  END LOOP;
  CLOSE C_USUARIOS;

  RETURN V_RESULTADO;
END;


FUNCTION FIDE_CONTAR_PRODUCTOS_POR_CATEGORIA_FN(P_CATEGORIA IN NUMBER) 
RETURN NUMBER IS
  CURSOR C_PRODUCTOS(P_ID_CATEGORIA NUMBER) IS
    SELECT ID_PRODUCTO, NOMBRE, ID_UNIDAD_MEDIDA, ID_ESTADO
    FROM FIDE_PRODUCTO_TB
    WHERE ID_CATEGORIA = P_ID_CATEGORIA;

  V_ID FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE;
  V_NOMBRE FIDE_PRODUCTO_TB.NOMBRE%TYPE;
  V_UMEDIDA FIDE_PRODUCTO_TB.ID_UNIDAD_MEDIDA%TYPE;
  V_ESTADO FIDE_PRODUCTO_TB.ID_ESTADO%TYPE;
  V_CONTADOR NUMBER := 0;

BEGIN
  OPEN C_PRODUCTOS(P_CATEGORIA);
  LOOP
    FETCH C_PRODUCTOS INTO V_ID, V_NOMBRE, V_UMEDIDA, V_ESTADO;
    EXIT WHEN C_PRODUCTOS%NOTFOUND;
    
    V_CONTADOR := V_CONTADOR + 1;
    
  END LOOP;
  CLOSE C_PRODUCTOS;
  
  RETURN V_CONTADOR;
END;


FUNCTION FIDE_PESO_PROMEDIO_POR_HABITAT_FN(P_HABITAT IN NUMBER) 
RETURN NUMBER IS
  CURSOR C_ANIMALES(P_ID_HABITAT NUMBER) IS
    SELECT ID_ANIMAL, NOMBRE_ANIMAL, EDAD, PESO
    FROM FIDE_ANIMAL_TB
    WHERE ID_HABITAT = P_ID_HABITAT;

  V_ID FIDE_ANIMAL_TB.ID_ANIMAL%TYPE;
  V_NOMBRE FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE;
  V_EDAD FIDE_ANIMAL_TB.EDAD%TYPE;
  V_PESO FIDE_ANIMAL_TB.PESO%TYPE;
  V_SUMA_PESO NUMBER := 0;
  V_CONTADOR NUMBER := 0;

BEGIN
  OPEN C_ANIMALES(P_HABITAT);
  LOOP
    FETCH C_ANIMALES INTO V_ID, V_NOMBRE, V_EDAD, V_PESO;
    EXIT WHEN C_ANIMALES%NOTFOUND;
    
    V_SUMA_PESO := V_SUMA_PESO + V_PESO;
    V_CONTADOR := V_CONTADOR + 1;
  END LOOP;
  CLOSE C_ANIMALES;
  
  IF V_CONTADOR > 0 THEN
    RETURN V_SUMA_PESO  / V_CONTADOR;
  ELSE
    RETURN 0;
  END IF;
END;

FUNCTION FIDE_OBTENER_DIRECCION_USUARIO_FN(
  P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2 IS
  V_ID_DIRECCION FIDE_USUARIO_TB.ID_DIRECCION%TYPE;
  V_DETALLE FIDE_DIRECCION_TB.DETALLE_DIRECCION%TYPE;
  V_PAIS FIDE_DIRECCION_TB.ID_PAIS%TYPE;
  V_PROVINCIA FIDE_DIRECCION_TB.ID_PROVINCIA%TYPE;
  V_RESULTADO VARCHAR2(1000);
BEGIN

  SELECT ID_DIRECCION INTO V_ID_DIRECCION
  FROM FIDE_USUARIO_TB
  WHERE ID_USUARIO = P_ID_USUARIO;
  SELECT DETALLE_DIRECCION, ID_PAIS, ID_PROVINCIA
  INTO V_DETALLE, V_PAIS, V_PROVINCIA
  FROM FIDE_DIRECCION_TB
  WHERE ID_DIRECCION = V_ID_DIRECCION;

  V_RESULTADO := 'DETALLE: ' || V_DETALLE || 
                 ' | PAIS: ' || V_PAIS || 
                 ' | PROVINCIA: ' || V_PROVINCIA;

  RETURN V_RESULTADO;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 'NO SE ENCONTRÓ DIRECCIÓN PARA EL USUARIO';
  WHEN OTHERS THEN
    RETURN 'ERROR INESPERADO: ' || SQLERRM;
END;



FUNCTION FIDE_TOTAL_FACTURAS_USUARIO_FN(P_USUARIO IN NUMBER) 
RETURN NUMBER IS
  CURSOR C_FACTURAS(P_ID_USUARIO NUMBER) IS
    SELECT ID_FACTURA, FECHA_REGISTRO, MONTO_TOTAL, SUBTOTAL
    FROM FIDE_FACTURA_TB
    WHERE ID_USUARIO = P_ID_USUARIO;

  V_ID FIDE_FACTURA_TB.ID_FACTURA%TYPE;
  V_FECHA FIDE_FACTURA_TB.FECHA_REGISTRO%TYPE;
  V_MONTO FIDE_FACTURA_TB.MONTO_TOTAL%TYPE;
  V_SUBTOTAL FIDE_FACTURA_TB.SUBTOTAL%TYPE;
  V_TOTAL_GENERAL NUMBER := 0;

BEGIN
  OPEN C_FACTURAS(P_USUARIO);
  LOOP
    FETCH C_FACTURAS INTO V_ID, V_FECHA, V_MONTO, V_SUBTOTAL;
    EXIT WHEN C_FACTURAS%NOTFOUND;
    
    V_TOTAL_GENERAL := V_TOTAL_GENERAL + V_MONTO;
  END LOOP;
  CLOSE C_FACTURAS;
  
  RETURN V_TOTAL_GENERAL;
END;

---DETALLE FACTURA
FUNCTION FIDE_DETALLE_FACTURA_CADENA_FN(P_FACTURA IN NUMBER) 
RETURN VARCHAR2 IS
  CURSOR C_DETALLE(P_ID_FACTURA NUMBER) IS
    SELECT CANTIDAD, PRECIO_UNITARIO, TOTAL
    FROM FIDE_DETALLE_FACTURA_TB
    WHERE ID_FACTURA = P_ID_FACTURA;

  V_CANTIDAD FIDE_DETALLE_FACTURA_TB.CANTIDAD%TYPE;
  V_PRECIO FIDE_DETALLE_FACTURA_TB.PRECIO_UNITARIO%TYPE;
  V_TOTAL FIDE_DETALLE_FACTURA_TB.TOTAL%TYPE;
  V_RESULTADO VARCHAR2(4000) := '';

BEGIN
  OPEN C_DETALLE(P_FACTURA);
  LOOP
    FETCH C_DETALLE INTO V_CANTIDAD, V_PRECIO, V_TOTAL;
    EXIT WHEN C_DETALLE%NOTFOUND;

    V_RESULTADO := V_RESULTADO || 
                   ' | CANTIDAD: ' || V_CANTIDAD || 
                   ' | PRECIO: ' || V_PRECIO || 
                   ' | TOTAL: ' || V_TOTAL || CHR(10);
  END LOOP;
  CLOSE C_DETALLE;
  
  RETURN V_RESULTADO;
END;

FUNCTION FIDE_CANTIDAD_TOTAL_INVENTARIO_FN(P_PRODUCTO IN NUMBER) 
RETURN NUMBER IS
  CURSOR C_INVENTARIO(P_ID_PRODUCTO NUMBER) IS
    SELECT CANTIDAD, FECHA_INGRESO
    FROM FIDE_INVENTARIO_TB
    WHERE ID_PRODUCTO = P_ID_PRODUCTO;

  V_CANTIDAD FIDE_INVENTARIO_TB.CANTIDAD%TYPE;
  V_FECHA FIDE_INVENTARIO_TB.FECHA_INGRESO%TYPE;
  V_TOTAL_CANTIDAD NUMBER := 0;

BEGIN
  OPEN C_INVENTARIO(P_PRODUCTO);
  LOOP
    FETCH C_INVENTARIO INTO V_CANTIDAD, V_FECHA;
    EXIT WHEN C_INVENTARIO%NOTFOUND;

    V_TOTAL_CANTIDAD := V_TOTAL_CANTIDAD + V_CANTIDAD;
  END LOOP;
  CLOSE C_INVENTARIO;

  RETURN V_TOTAL_CANTIDAD;
END;

END FIDE_PROYECTO_FINAL_PCK;