---PROCEDIMIENTOS ALMACENADOS (CRUD DE TODAS LAS TABLAS)
--TABLA DE ESTADOS
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO, DESCRIPCION_ESTADO)
   VALUES(P_ID_ESTADO, P_NOMBRE_ESTADO, P_DESCRIPCION_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ESTADO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_ESTADO_SP(
P_ID_ESTADO IN FIDE_ESTADOS_TB.ID_ESTADO%TYPE,
P_NOMBRE_ESTADO IN FIDE_ESTADOS_TB.NOMBRE_ESTADO%TYPE, 
P_DESCRIPCION_ESTADO IN FIDE_ESTADOS_TB.DESCRIPCION_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO,
            DESCRIPCION_ESTADO = P_DESCRIPCION_ESTADO
    WHERE ID_ESTADO = P_ID_ESTADO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ESTADO_SP;
/

--TABLA DE GENERO
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_GENERO_TB (ID_GENERO, GENERO, ID_ESTADO)
   VALUES(P_ID_GENERO, P_GENERO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_GENERO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE,
P_GENERO IN FIDE_GENERO_TB.GENERO%TYPE, 
P_ID_ESTADO IN FIDE_GENERO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET GENERO = P_GENERO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_GENERO_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_GENERO_SP(
P_ID_GENERO IN FIDE_GENERO_TB.ID_GENERO%TYPE
)IS
    BEGIN
    UPDATE FIDE_GENERO_TB
    SET ID_ESTADO = 2
    WHERE ID_GENERO = P_ID_GENERO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_GENERO_SP;
/

--TABLA DE TIPO
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_TIPO_TB (ID_TIPO, NOMBRE_TIPO, DESCRIPCION_TIPO, ID_ESTADO)
   VALUES(P_ID_TIPO, P_NOMBRE_TIPO, P_DESCRIPCION_TIPO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_TIPO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE,
P_NOMBRE_TIPO IN FIDE_TIPO_TB.NOMBRE_TIPO%TYPE, 
P_DESCRIPCION_TIPO IN FIDE_TIPO_TB.DESCRIPCION_TIPO%TYPE,
P_ID_ESTADO IN FIDE_TIPO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET NOMBRE_TIPO = P_NOMBRE_TIPO,
            DESCRIPCION_TIPO = P_DESCRIPCION_TIPO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_TIPO_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_TIPO_SP(
P_ID_TIPO IN FIDE_TIPO_TB.ID_TIPO%TYPE
)IS
    BEGIN
    UPDATE FIDE_TIPO_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO = P_ID_TIPO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_TIPO_SP;
/

--TABLA DE HABITAT
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_HABITAT_TB (ID_HABITAT, NOMBRE_HABITAT, DESCRIPCION_HABITAT, ID_ESTADO)
   VALUES(P_ID_HABITAT, P_NOMBRE_HABITAT, P_DESCRIPCION_HABITAT, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_HABITAT_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE,
P_NOMBRE_HABITAT IN FIDE_HABITAT_TB.NOMBRE_HABITAT%TYPE, 
P_DESCRIPCION_HABITAT IN FIDE_HABITAT_TB.DESCRIPCION_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_HABITAT_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET NOMBRE_HABITAT = P_NOMBRE_HABITAT,
            DESCRIPCION_HABITAT = P_DESCRIPCION_HABITAT,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_HABITAT_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_HABITAT_SP(
P_ID_HABITAT IN FIDE_HABITAT_TB.ID_HABITAT%TYPE
)IS
    BEGIN
    UPDATE FIDE_HABITAT_TB
    SET ID_ESTADO = 2
    WHERE ID_HABITAT = P_ID_HABITAT;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_HABITAT_SP;
/

--TABLA DE RUTINA
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_RUTINA_TB (ID_RUTINA, NOMBRE_RUTINA, ID_ESTADO)
   VALUES(P_ID_RUTINA, P_NOMBRE_RUTINA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_RUTINA_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_NOMBRE_RUTINA IN FIDE_RUTINA_TB.NOMBRE_RUTINA%TYPE, 
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET NOMBRE_RUTINA = P_NOMBRE_RUTINA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_RUTINA_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
)IS
    BEGIN
    UPDATE FIDE_RUTINA_TB
    SET ID_ESTADO = 2
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_RUTINA_SP;
/

--TABLA DE MARCA_ALIMENTO
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_MARCA_ALIMENTO_TB (ID_MARCA_ALIMENTO, NOMBRE, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_MARCA_ALIMENTO, P_NOMBRE, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_MARCA_ALIMENTO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE,
P_NOMBRE IN FIDE_MARCA_ALIMENTO_TB.NOMBRE%TYPE, 
P_DESCRIPCION IN FIDE_MARCA_ALIMENTO_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_MARCA_ALIMENTO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET NOMBRE = P_NOMBRE,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_MARCA_ALIMENTO_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_MARCA_ALIMENTO_SP(
P_ID_MARCA_ALIMENTO IN FIDE_MARCA_ALIMENTO_TB.ID_MARCA_ALIMENTO%TYPE
)IS
    BEGIN
    UPDATE FIDE_MARCA_ALIMENTO_TB
    SET ID_ESTADO = 2
    WHERE ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_MARCA_ALIMENTO_SP;
/

--TABLA DE ALIMENTACION
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_ALIMENTACION_SP(
P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ALIMENTACION_TB (ID_ALIMENTACION, CANTIDAD, HORARIO, FRECUENCIA, ID_MARCA_ALIMENTO, ID_ESTADO, ID_RUTINA) 
   VALUES(P_ID_ALIMENTACION, P_CANTIDAD, P_HORARIO, P_FRECUENCIA, P_ID_MARCA_ALIMENTO, P_ID_ESTADO, P_ID_RUTINA);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ALIMENTACION_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE,
    P_CANTIDAD IN FIDE_ALIMENTACION_TB.CANTIDAD%TYPE,
    P_HORARIO IN FIDE_ALIMENTACION_TB.HORARIO%TYPE,
    P_FRECUENCIA IN FIDE_ALIMENTACION_TB.FRECUENCIA%TYPE,
    P_ID_MARCA_ALIMENTO IN FIDE_ALIMENTACION_TB.ID_MARCA_ALIMENTO%TYPE,
    P_ID_ESTADO IN FIDE_ALIMENTACION_TB.ID_ESTADO%TYPE,
    P_ID_RUTINA IN FIDE_ALIMENTACION_TB.ID_RUTINA%TYPE
) IS
BEGIN
    UPDATE FIDE_ALIMENTACION_TB
    SET CANTIDAD = P_CANTIDAD,
            HORARIO = P_HORARIO,
            FRECUENCIA = P_FRECUENCIA,
            ID_MARCA_ALIMENTO = P_ID_MARCA_ALIMENTO,
            ID_ESTADO = P_ID_ESTADO,
            ID_RUTINA = P_ID_RUTINA
    WHERE ID_ALIMENTACION = P_ID_ALIMENTACION; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ALIMENTACION_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_ALIMENTACION_SP(
    P_ID_ALIMENTACION IN FIDE_ALIMENTACION_TB.ID_ALIMENTACION%TYPE
)IS
BEGIN
    UPDATE FIDE_ALIMENTACION_TB
    SET ID_ESTADO = 2
    WHERE ID_ALIMENTACION = P_ID_ALIMENTACION;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ALIMENTACION_SP;

--TABLA DE ANIMAL
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_ANIMAL_SP(
P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ANIMAL_TB (ID_ANIMAL, NOMBRE_ANIMAL, FECHA_INGRESO, EDAD, PESO, OBSERVACION, ID_GENERO, ID_TIPO, ID_HABITAT, ID_ESTADO, ID_ALIMENTACION) 
   VALUES(P_ID_ANIMAL, P_NOMBRE_ANIMAL, P_FECHA_INGRESO, P_EDAD, P_PESO, P_OBSERVACION, P_ID_GENERO, P_ID_TIPO, P_ID_HABITAT, P_ID_ESTADO, P_ID_ALIMENTACION);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ANIMAL_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE,
    P_NOMBRE_ANIMAL IN FIDE_ANIMAL_TB.NOMBRE_ANIMAL%TYPE,
    P_FECHA_INGRESO IN FIDE_ANIMAL_TB.FECHA_INGRESO%TYPE,
    P_EDAD IN FIDE_ANIMAL_TB.EDAD%TYPE,
    P_PESO IN FIDE_ANIMAL_TB.PESO%TYPE,
    P_OBSERVACION IN FIDE_ANIMAL_TB.OBSERVACION%TYPE,
    P_ID_GENERO IN FIDE_ANIMAL_TB.ID_GENERO%TYPE,
    P_ID_TIPO IN FIDE_ANIMAL_TB.ID_TIPO%TYPE,
    P_ID_HABITAT IN FIDE_ANIMAL_TB.ID_HABITAT%TYPE,
    P_ID_ESTADO IN FIDE_ANIMAL_TB.ID_ESTADO%TYPE,
    P_ID_ALIMENTACION IN FIDE_ANIMAL_TB.ID_ALIMENTACION%TYPE
) IS
BEGIN
    UPDATE FIDE_ANIMAL_TB
    SET NOMBRE_ANIMAL = P_NOMBRE_ANIMAL,
            FECHA_INGRESO = P_FECHA_INGRESO,
            EDAD = P_EDAD,
            PESO = P_PESO,
            OBSERVACION = P_OBSERVACION,
            ID_GENERO = P_ID_GENERO,
            ID_TIPO = P_ID_TIPO,
            ID_HABITAT = P_ID_HABITAT,
            ID_ESTADO = P_ID_ESTADO,
            ID_ALIMENTACION = P_ID_ALIMENTACION
    WHERE ID_ANIMAL = P_ID_ANIMAL; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ANIMAL_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_ANIMAL_SP(
    P_ID_ANIMAL IN FIDE_ANIMAL_TB.ID_ANIMAL%TYPE
)IS
BEGIN
    UPDATE FIDE_ANIMAL_TB
    SET ID_ESTADO = 2
    WHERE ID_ANIMAL = P_ID_ANIMAL;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ANIMAL_SP;
/

--TABLA DE ROL
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_ROL_TB (ID_ROL, NOMBRE_ROL, DESCRIPCION, ID_ESTADO)
   VALUES(P_ID_ROL, P_NOMBRE_ROL, P_DESCRIPCION, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_ROL_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE,
P_NOMBRE_ROL IN FIDE_ROL_TB.NOMBRE_ROL%TYPE, 
P_DESCRIPCION IN FIDE_ROL_TB.DESCRIPCION%TYPE,
P_ID_ESTADO IN FIDE_ROL_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET NOMBRE_ROL = P_NOMBRE_ROL,
            DESCRIPCION = P_DESCRIPCION,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_ROL_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_ROL_SP(
P_ID_ROL IN FIDE_ROL_TB.ID_ROL%TYPE
)IS
    BEGIN
    UPDATE FIDE_ROL_TB
    SET ID_ESTADO = 2
    WHERE ID_ROL = P_ID_ROL;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_ROL_SP;
/

--TABLA DE USUARIO
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_USUARIO_SP(
P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
   INSERT INTO FIDE_USUARIO_TB (ID_USUARIO, NOMBRE, FECHA_REGISTRO, TELEFONO, CORREO, ID_ESTADO, ID_ROL) 
   VALUES(P_ID_USUARIO, P_NOMBRE, P_FECHA_REGISTRO, P_TELEFONO, P_CORREO, P_ID_ESTADO, P_ID_ROL);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_USUARIO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE,
    P_NOMBRE IN FIDE_USUARIO_TB.NOMBRE%TYPE,
    P_FECHA_REGISTRO IN FIDE_USUARIO_TB.FECHA_REGISTRO%TYPE,
    P_TELEFONO IN FIDE_USUARIO_TB.TELEFONO%TYPE,
    P_CORREO IN FIDE_USUARIO_TB.CORREO%TYPE,
    P_ID_ESTADO IN FIDE_USUARIO_TB.ID_ESTADO%TYPE,
    P_ID_ROL IN FIDE_USUARIO_TB.ID_ROL%TYPE
) IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET NOMBRE = P_NOMBRE,
            FECHA_REGISTRO = P_FECHA_REGISTRO,
            TELEFONO = P_TELEFONO,
            CORREO = P_CORREO,
            ID_ESTADO = P_ID_ESTADO,
            ID_ROL = P_ID_ROL
    WHERE ID_USUARIO = P_ID_USUARIO; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_USUARIO_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_USUARIO_SP(
    P_ID_USUARIO IN FIDE_USUARIO_TB.ID_USUARIO%TYPE
)IS
BEGIN
    UPDATE FIDE_USUARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_USUARIO = P_ID_USUARIO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_USUARIO_SP;
/

--TABLA DE RUTINA
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_RUTINA_SP(
P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
P_DIA IN FIDE_RUTINA_TB.DIA%TYPE,
P_HORA_INICIO IN FIDE_RUTINA_TB.HORA_INICIO%TYPE,
P_HORA_FINAL IN FIDE_RUTINA_TB.HORA_FINAL%TYPE,
P_ID_USUARIO IN FIDE_RUTINA_TB.ID_USUARIO%TYPE,
P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE,
) IS
BEGIN
   INSERT INTO FIDE_RUTINA_TB (ID_RUTINA, DIA, HORA_INICIO, HORA_FINAL, ID_USUARIO, ID_ESTADO) 
   VALUES(P_ID_RUTINA, P_DIA, P_HORA_INICIO, P_HORA_FINAL, P_ID_USUARIO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_RUTINA_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_RUTINA_SP(
    P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE,
    P_DIA IN FIDE_RUTINA_TB.DIA%TYPE,
    P_HORA_INICIO IN FIDE_RUTINA_TB.HORA_INICIO%TYPE,
    P_HORA_FINAL IN FIDE_RUTINA_TB.HORA_FINAL%TYPE,
    P_ID_USUARIO IN FIDE_RUTINA_TB.ID_USUARIO%TYPE,
    P_ID_ESTADO IN FIDE_RUTINA_TB.ID_ESTADO%TYPE,
) IS
BEGIN
    UPDATE FIDE_RUTINA_TB
    SET DIA = P_DIA,
            HORA_INICIO = P_HORA_INICIO,
            HORA_FINAL = P_HORA_FINAL,
            ID_USUARIO = P_ID_USUARIO,
            ID_ESTADO = P_ID_ESTADO,
    WHERE ID_RUTINA = P_ID_RUTINA; 
    COMMIT; 
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_RUTINA_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_RUTINA_SP(
    P_ID_RUTINA IN FIDE_RUTINA_TB.ID_RUTINA%TYPE
)IS
BEGIN
    UPDATE FIDE_RUTINA_TB
    SET ID_ESTADO = 2
    WHERE ID_RUTINA = P_ID_RUTINA;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_RUTINA_SP;

--TABLA DE PAIS
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PAIS_TB (ID_PAIS, NOMBRE_PAIS, ID_ESTADO)
   VALUES(P_ID_PAIS, P_NOMBRE_PAIS, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PAIS_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE,
P_NOMBRE_PAIS IN FIDE_PAIS_TB.NOMBRE_PAIS%TYPE, 
P_ID_ESTADO IN FIDE_PAIS_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET NOMBRE_PAIS = P_NOMBRE_PAIS,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PAIS_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_PAIS_SP(
P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
)IS
    BEGIN
    UPDATE FIDE_PAIS_TB
    SET ID_ESTADO = 2
    WHERE ID_PAIS = P_ID_PAIS;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PAIS_SP;
/

--TABLA DE PROVINCIA
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_PROVINCIA_TB (ID_PROVINCIA, NOMBRE_PROVINCIA, ID_ESTADO)
   VALUES(P_ID_PROVINCIA, P_NOMBRE_PROVINCIA, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_PROVINCIA_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
P_NOMBRE_PROVINCIA IN FIDE_PROVINCIA_TB.NOMBRE_PROVINCIA%TYPE, 
P_ID_ESTADO IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET NOMBRE_PROVINCIA = P_NOMBRE_PROVINCIA,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_PROVINCIA_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_PROVINCIA_SP(
P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
)IS
    BEGIN
    UPDATE FIDE_PROVINCIA_TB
    SET ID_ESTADO = 2
    WHERE ID_PROVINCIA = P_ID_PROVINCIA;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_PROVINCIA_SP;
/

--TABLA DE CANTON
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_CANTON_TB (ID_CANTON, NOMBRE_CANTON, ID_ESTADO)
   VALUES(P_ID_CANTON, P_NOMBRE_CANTON, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_CANTON_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE,
P_NOMBRE_CANTON IN FIDE_CANTON_TB.NOMBRE_CANTON%TYPE, 
P_ID_ESTADO IN FIDE_CANTON_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET NOMBRE_CANTON = P_NOMBRE_CANTON,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_CANTON_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_CANTON_SP(
P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
)IS
    BEGIN
    UPDATE FIDE_CANTON_TB
    SET ID_ESTADO = 2
    WHERE ID_CANTON = P_ID_CANTON;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_CANTON_SP;
/

--TABLA DE DISTRITO
--INSERTAR
CREATE OR REPLACE PROCEDURE FIDE_INSERTAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
) IS
BEGIN
   INSERT INTO FIDE_DISTRITO_TB (ID_DISTRITO, NOMBRE_DISTRITO, ID_ESTADO)
   VALUES(P_ID_DISTRITO, P_NOMBRE_DISTRITO, P_ID_ESTADO);
   COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_INSERTAR_DISTRITO_SP;
/

--MODIFICAR
CREATE OR REPLACE PROCEDURE FIDE_MODIFICAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
P_NOMBRE_DISTRITO IN FIDE_DISTRITO_TB.NOMBRE_DISTRITO%TYPE, 
P_ID_ESTADO IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET NOMBRE_DISTRITO = P_NOMBRE_DISTRITO,
            ID_ESTADO = P_ID_ESTADO
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_MODIFICAR_DISTRITO_SP;
/

--ELIMINAR
CREATE OR REPLACE PROCEDURE FIDE_ELIMINAR_DISTRITO_SP(
P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
)IS
    BEGIN
    UPDATE FIDE_DISTRITO_TB
    SET ID_ESTADO = 2
    WHERE ID_DISTRITO = P_ID_DISTRITO;
    COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: '|| SQLERRM);
END FIDE_ELIMINAR_DISTRITO_SP;
/