--Vistas de los atributos de cada tabla

CREATE OR REPLACE VIEW vista_fide_estados_tb AS
SELECT *
FROM FIDE_ESTADOS_TB;

CREATE OR REPLACE VIEW vista_fide_genero_tb AS
SELECT *
FROM FIDE_GENERO_TB;

CREATE OR REPLACE VIEW vista_fide_tipo_tb AS
SELECT *
FROM FIDE_TIPO_TB;

CREATE OR REPLACE VIEW vista_fide_habitat_tb AS
SELECT *
FROM FIDE_HABITAT_TB;

CREATE OR REPLACE VIEW vista_fide_rutina_tb AS
SELECT *
FROM FIDE_RUTINA_TB;

CREATE OR REPLACE VIEW vista_fide_marca_alimento_tb AS
SELECT *
FROM FIDE_MARCA_ALIMENTO_TB;

CREATE OR REPLACE VIEW vista_fide_alimentacion_tb AS
SELECT *
FROM FIDE_ALIMENTACION_TB;

CREATE OR REPLACE VIEW vista_fide_animal_tb AS
SELECT *
FROM FIDE_ANIMAL_TB;

CREATE OR REPLACE VIEW vista_fide_rol_tb AS
SELECT *
FROM FIDE_ROL_TB;

CREATE OR REPLACE VIEW vista_fide_usuario_tb AS
SELECT *
FROM FIDE_USUARIO_TB;

CREATE OR REPLACE VIEW vista_fide_horario_tb AS
SELECT *
FROM FIDE_HORARIO_TB;

CREATE OR REPLACE VIEW vista_fide_pais_tb AS
SELECT *
FROM FIDE_PAIS_TB;

CREATE OR REPLACE VIEW vista_fide_provincia_tb AS
SELECT *
FROM FIDE_PROVINCIA_TB;

CREATE OR REPLACE VIEW vista_fide_canton_tb AS
SELECT *
FROM FIDE_CANTON_TB;

CREATE OR REPLACE VIEW vista_fide_distrito_tb AS
SELECT *
FROM FIDE_DISTRITO_TB;

CREATE OR REPLACE VIEW vista_fide_direccion_tb AS
SELECT *
FROM FIDE_DIRECCION_TB;

CREATE OR REPLACE VIEW vista_fide_telefono_tb AS
SELECT *
FROM FIDE_TELEFONO_TB;

CREATE OR REPLACE VIEW vista_fide_correo_tb AS
SELECT *
FROM FIDE_CORREO_TB;

CREATE OR REPLACE VIEW vista_fide_producto_tb AS
SELECT *
FROM FIDE_PRODUCTO_TB;

CREATE OR REPLACE VIEW vista_fide_unidad_medida_tb AS
SELECT *
FROM FIDE_UNIDAD_MEDIDA_TB;

CREATE OR REPLACE VIEW vista_fide_metodo_pago_tb AS
SELECT *
FROM FIDE_METODO_PAGO_TB;

CREATE OR REPLACE VIEW vista_fide_factura_tb AS
SELECT *
FROM FIDE_FACTURA_TB;

CREATE OR REPLACE VIEW vista_fide_detalle_factura_tb AS
SELECT *
FROM FIDE_DETALLE_FACTURA_TB;

CREATE OR REPLACE VIEW vista_fide_detalle_alimentacion_tb AS
SELECT *
FROM FIDE_DETALLE_ALIMENTACION_TB;

CREATE OR REPLACE VIEW vista_fide_detalle_rutina_tb AS
SELECT *
FROM FIDE_DETALLE_RUTINA_TB;
