-- ANIMALES POR HABITAT
CREATE OR REPLACE VIEW vista_animales_por_habitat AS
SELECT h.NOMBRE_HABITAT,
       COUNT(a.ID_ANIMAL) AS TOTAL_ANIMALES
FROM FIDE_HABITAT_TB h
LEFT JOIN FIDE_ANIMAL_TB a
  ON h.ID_HABITAT = a.ID_HABITAT
GROUP BY h.NOMBRE_HABITAT;

-- ALIMENTO POR MARCA
CREATE OR REPLACE VIEW vista_alimentacion_por_marca AS
SELECT m.NOMBRE         AS MARCA_ALIMENTO,
       SUM(a.CANTIDAD)  AS CANTIDAD_TOTAL
FROM FIDE_MARCA_ALIMENTO_TB m
JOIN FIDE_ALIMENTACION_TB a
  ON m.ID_MARCA_ALIMENTO = a.ID_MARCA_ALIMENTO
GROUP BY m.NOMBRE;

-- ANIMALES POR TIPO Y GENERO
CREATE OR REPLACE VIEW vista_animales_detalle AS
SELECT a.ID_ANIMAL,
       a.NOMBRE_ANIMAL,
       g.GENERO,
       t.NOMBRE_TIPO
FROM FIDE_ANIMAL_TB a
JOIN FIDE_GENERO_TB g
  ON a.ID_GENERO = g.ID_GENERO
JOIN FIDE_TIPO_TB t
  ON a.ID_TIPO = t.ID_TIPO;

-- USUARIOS POR ROL
CREATE OR REPLACE VIEW vista_usuarios_por_rol AS
SELECT r.NOMBRE_ROL,
       COUNT(u.ID_USUARIO) AS TOTAL_USUARIOS
FROM FIDE_ROL_TB r
LEFT JOIN FIDE_USUARIO_TB u
  ON r.ID_ROL = u.ID_ROL
GROUP BY r.NOMBRE_ROL;

-- FACTURAS TOTALES POR USUARIO
CREATE OR REPLACE VIEW vista_facturas_por_usuario AS
SELECT u.NOMBRE         AS USUARIO,
       COUNT(f.ID_FACTURA)  AS NUM_FACTURAS,
       SUM(f.MONTO_TOTAL)   AS TOTAL_FACTURAS
FROM FIDE_USUARIO_TB u
LEFT JOIN FIDE_FACTURA_TB f
  ON u.ID_USUARIO = f.ID_USUARIO
GROUP BY u.NOMBRE;

-- DETALLE DE FACTURAS CON PRODUCTOS
CREATE OR REPLACE VIEW vista_detalle_factura_completo AS
SELECT df.ID_DETALLE,
       f.ID_FACTURA,
       p.NOMBRE             AS PRODUCTO,
       df.CANTIDAD,
       df.TOTAL
FROM FIDE_DETALLE_FACTURA_TB df
JOIN FIDE_FACTURA_TB f
  ON df.ID_FACTURA = f.ID_FACTURA
JOIN FIDE_PRODUCTO_TB p
  ON df.ID_PRODUCTO = p.ID_PRODUCTO;

-- INVENTARIO DE PRODUCTOS
CREATE OR REPLACE VIEW vista_inventario_productos AS
SELECT p.NOMBRE   AS PRODUCTO,
       i.CANTIDAD,
       i.FECHA_INGRESO
FROM FIDE_INVENTARIO_TB i
JOIN FIDE_PRODUCTO_TB p
  ON i.ID_PRODUCTO = p.ID_PRODUCTO;

-- ENTREGA POR USUARIO
CREATE OR REPLACE VIEW vista_entregas_por_usuario AS
SELECT u.NOMBRE         AS USUARIO,
       COUNT(e.ID_ENTREGA) AS TOTAL_ENTREGAS
FROM FIDE_USUARIO_TB u
LEFT JOIN FIDE_ENTREGA_TB e
  ON u.ID_USUARIO = e.ID_USUARIO
GROUP BY u.NOMBRE;

-- PRODUCTOS DISPONIBLES CON CATEGORIA Y ESTADO
CREATE OR REPLACE VIEW vista_productos_disponibles AS
SELECT p.NOMBRE AS producto,
       c.NOMBRE_CATEGORIA AS categoria,
       e.NOMBRE_ESTADO AS estado
FROM FIDE_PRODUCTO_TB p
JOIN FIDE_CATEGORIA_TB c ON p.ID_CATEGORIA = c.ID_CATEGORIA
JOIN FIDE_ESTADOS_TB e ON p.ID_ESTADO = e.ID_ESTADO
WHERE e.NOMBRE_ESTADO = 'Activo';

-- ENTREGAAS DEL ULTIMO MES
CREATE OR REPLACE VIEW vista_entregas_resumen AS
SELECT e.ID_ENTREGA,
       e.FECHA,
       u.NOMBRE AS nombre_usuario,
       d.DETALLE_DIRECCION
FROM FIDE_ENTREGA_TB e
JOIN FIDE_USUARIO_TB u ON e.ID_USUARIO = u.ID_USUARIO
JOIN FIDE_DIRECCION_TB d ON e.ID_DIRECCION = d.ID_DIRECCION
WHERE e.FECHA >= SYSDATE - 30;